
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 14 2025 22:59:37 IST (Nov 14 2025 17:29:37 UTC)

// Verification Directory fv/master 

module master(clk, sw, btn, led, RGB0, RGB1, spi_sclk_out,
     spi_mosi_out, spi_cs_n_out, spi_miso_in);
  input clk, spi_miso_in;
  input [15:0] sw;
  input [3:0] btn;
  output [15:0] led;
  output [2:0] RGB0, RGB1;
  output spi_sclk_out, spi_mosi_out;
  output [7:0] spi_cs_n_out;
  wire clk, spi_miso_in;
  wire [15:0] sw;
  wire [3:0] btn;
  wire [15:0] led;
  wire [2:0] RGB0, RGB1;
  wire spi_sclk_out, spi_mosi_out;
  wire [7:0] spi_cs_n_out;
  wire [31:0] timer_cnt;
  wire [3:0] ctrl_state;
  wire [2:0] spi_state;
  wire [2:0] ctrl_gw_idx;
  wire [7:0] ctrl_latched_addr;
  wire [2:0] ctrl_latched_id;
  wire [15:0] ctrl_latched_write_data;
  wire [31:0] db_latch_cnt;
  wire [31:0] db_read_cnt;
  wire [31:0] db_write_cnt;
  wire [15:0] master_data_rd;
  wire [15:0] master_cmd_packet;
  wire [15:0] spi_shifter_in;
  wire [15:0] master_data_wr;
  wire [5:0] spi_bitcnt;
  wire [15:0] spi_divcnt;
  wire [15:0] spi_shifter_out;
  wire ctrl_btn_latch_db, ctrl_btn_read_s_db, ctrl_btn_write_s_db,
       ctrl_last_op_was_write, ctrl_latched_global, ctrl_timer_done,
       ctrl_timer_start, db_latch_sync0;
  wire db_latch_sync1, db_read_sync0, db_read_sync1, db_write_sync0,
       db_write_sync1, inc_add_73_46_n_237, inc_add_73_46_n_240,
       inc_add_73_46_n_245;
  wire inc_add_73_46_n_252, inc_add_73_46_n_255, inc_add_73_46_n_262,
       inc_add_73_46_n_265, inc_add_73_46_n_270, inc_add_73_46_n_277,
       inc_add_73_46_n_280, inc_add_73_46_n_285;
  wire inc_add_73_46_n_292, inc_add_73_46_n_295, inc_add_73_46_n_300,
       inc_add_73_46_n_305, inc_add_73_46_n_310, inc_add_113_46_n_237,
       inc_add_113_46_n_240, inc_add_113_46_n_245;
  wire inc_add_113_46_n_252, inc_add_113_46_n_255,
       inc_add_113_46_n_262, inc_add_113_46_n_265,
       inc_add_113_46_n_270, inc_add_113_46_n_277,
       inc_add_113_46_n_280, inc_add_113_46_n_285;
  wire inc_add_113_46_n_292, inc_add_113_46_n_295,
       inc_add_113_46_n_300, inc_add_113_46_n_305,
       inc_add_113_46_n_310, inc_add_153_44_n_237,
       inc_add_153_44_n_240, inc_add_153_44_n_245;
  wire inc_add_153_44_n_252, inc_add_153_44_n_255,
       inc_add_153_44_n_262, inc_add_153_44_n_265,
       inc_add_153_44_n_270, inc_add_153_44_n_277,
       inc_add_153_44_n_280, inc_add_153_44_n_285;
  wire inc_add_153_44_n_292, inc_add_153_44_n_295,
       inc_add_153_44_n_300, inc_add_153_44_n_305,
       inc_add_153_44_n_310, inc_add_186_40_n_255,
       inc_add_186_40_n_262, inc_add_186_40_n_265;
  wire inc_add_186_40_n_272, inc_add_186_40_n_275,
       inc_add_186_40_n_280, inc_add_186_40_n_285,
       inc_add_186_40_n_292, inc_add_186_40_n_295,
       inc_add_186_40_n_300, inc_add_186_40_n_307;
  wire inc_add_186_40_n_310, inc_add_186_40_n_315,
       inc_add_186_40_n_322, inc_add_186_40_n_327,
       inc_add_186_40_n_330, inc_add_186_40_n_335,
       inc_add_186_40_n_342, inc_add_186_40_n_345;
  wire inc_add_186_40_n_352, inc_add_186_40_n_355,
       inc_add_186_40_n_360, inc_add_186_40_n_367,
       inc_add_186_40_n_370, inc_add_186_40_n_375,
       inc_add_186_40_n_382, inc_add_186_40_n_385;
  wire inc_add_186_40_n_390, inc_add_186_40_n_395,
       inc_add_186_40_n_400, master_spi_busy, master_start_tx,
       master_tx_done, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_183, n_184, n_185, n_186;
  wire n_187, n_188, n_189, n_190, n_191, n_192, n_193, n_194;
  wire n_195, n_196, n_197, n_198, n_199, n_200, n_201, n_202;
  wire n_203, n_204, n_205, n_206, n_207, n_208, n_209, n_210;
  wire n_211, n_212, n_213, n_214, n_215, n_216, n_217, n_218;
  wire n_219, n_220, n_221, n_222, n_223, n_224, n_225, n_226;
  wire n_227, n_228, n_229, n_230, n_231, n_232, n_233, n_234;
  wire n_235, n_236, n_237, n_238, n_239, n_240, n_241, n_242;
  wire n_243, n_244, n_245, n_246, n_247, n_248, n_249, n_250;
  wire n_251, n_252, n_253, n_254, n_255, n_256, n_257, n_258;
  wire n_259, n_260, n_261, n_262, n_263, n_264, n_265, n_266;
  wire n_267, n_268, n_269, n_270, n_271, n_272, n_273, n_274;
  wire n_275, n_276, n_277, n_278, n_279, n_280, n_281, n_282;
  wire n_283, n_284, n_285, n_286, n_287, n_288, n_292, n_293;
  wire n_294, n_295, n_296, n_297, n_298, n_299, n_300, n_301;
  wire n_302, n_303, n_304, n_305, n_306, n_307, n_308, n_309;
  wire n_310, n_311, n_312, n_313, n_314, n_315, n_317, n_318;
  wire n_319, n_320, n_321, n_322, n_323, n_324, n_325, n_327;
  wire n_328, n_329, n_330, n_331, n_333, n_334, n_335, n_336;
  wire n_337, n_338, n_339, n_340, n_341, n_342, n_343, n_344;
  wire n_345, n_346, n_347, n_348, n_349, n_350, n_351, n_352;
  wire n_353, n_354, n_356, n_357, n_358, n_359, n_360, n_361;
  wire n_362, n_363, n_364, n_365, n_366, n_367, n_368, n_369;
  wire n_370, n_371, n_372, n_373, n_375, n_376, n_377, n_378;
  wire n_379, n_380, n_381, n_382, n_383, n_384, n_385, n_386;
  wire n_387, n_388, n_389, n_390, n_391, n_392, n_393, n_394;
  wire n_395, n_396, n_397, n_398, n_399, n_400, n_401, n_402;
  wire n_403, n_404, n_405, n_406, n_407, n_408, n_409, n_411;
  wire n_412, n_413, n_414, n_415, n_416, n_417, n_418, n_419;
  wire n_420, n_421, n_422, n_423, n_424, n_425, n_426, n_427;
  wire n_429, n_430, n_431, n_432, n_433, n_434, n_435, n_436;
  wire n_437, n_438, n_439, n_440, n_441, n_442, n_443, n_444;
  wire n_445, n_448, n_449, n_450, n_451, n_452, n_453, n_454;
  wire n_455, n_456, n_457, n_458, n_459, n_460, n_461, n_462;
  wire n_463, n_464, n_465, n_466, n_467, n_468, n_469, n_470;
  wire n_471, n_472, n_473, n_474, n_475, n_476, n_477, n_478;
  wire n_479, n_484, n_485, n_486, spi_active, timer_running;
  assign RGB1[0] = RGB1[2];
  DFCNQD1 ctrl_timer_done_reg(.CDN (n_12), .CP (clk), .D (n_448), .Q
       (ctrl_timer_done));
  OA31D1 g11006__2398(.A1 (timer_cnt[29]), .A2 (timer_cnt[30]), .A3
       (n_373), .B (timer_running), .Z (n_448));
  AO21D1 g11007__5107(.A1 (n_372), .A2 (timer_cnt[28]), .B
       (timer_cnt[31]), .Z (n_373));
  OR4D1 g11008__6260(.A1 (timer_cnt[27]), .A2 (timer_cnt[25]), .A3
       (timer_cnt[26]), .A4 (n_371), .Z (n_372));
  AN4XD1 g11009__4319(.A1 (n_370), .A2 (timer_cnt[22]), .A3
       (timer_cnt[23]), .A4 (timer_cnt[21]), .Z (n_371));
  OA31D1 g11010__8428(.A1 (timer_cnt[17]), .A2 (timer_cnt[18]), .A3
       (n_369), .B (timer_cnt[24]), .Z (n_370));
  AO211D1 g11011__5526(.A1 (n_368), .A2 (timer_cnt[15]), .B
       (timer_cnt[19]), .C (timer_cnt[20]), .Z (n_369));
  OA21D1 g11012__6783(.A1 (n_367), .A2 (timer_cnt[14]), .B
       (timer_cnt[16]), .Z (n_368));
  OA31D1 g11013__3680(.A1 (timer_cnt[11]), .A2 (timer_cnt[12]), .A3
       (n_366), .B (timer_cnt[13]), .Z (n_367));
  DFCNQD2 led_green_write_wire_reg(.CDN (n_12), .CP (clk), .D (n_365),
       .Q (RGB1[1]));
  AO21D1 g11015__1617(.A1 (n_363), .A2 (timer_cnt[9]), .B
       (timer_cnt[10]), .Z (n_366));
  DFCNQD1 ctrl_timer_start_reg(.CDN (n_12), .CP (clk), .D (n_364), .Q
       (ctrl_timer_start));
  IND3D1 g11017__2802(.A1 (n_378), .B1 (n_384), .B2 (n_362), .ZN
       (n_365));
  DFCNQD1 master_start_tx_reg(.CDN (n_12), .CP (clk), .D (n_361), .Q
       (master_start_tx));
  ND2D1 g11019__1705(.A1 (n_362), .A2 (n_359), .ZN (n_364));
  AO31D1 g11020__5122(.A1 (n_357), .A2 (n_358), .A3 (timer_cnt[0]), .B
       (timer_cnt[8]), .Z (n_363));
  CKND2D1 g11021__8246(.A1 (n_382), .A2 (n_359), .ZN (n_378));
  CKND1 g11022(.I (n_361), .ZN (n_376));
  IND2D1 g11023__7098(.A1 (n_379), .B1 (master_tx_done), .ZN (n_362));
  AOI21D1 g11024__6131(.A1 (n_383), .A2 (n_377), .B (master_spi_busy),
       .ZN (n_361));
  DFCNQD1 master_tx_done_reg(.CDN (n_12), .CP (clk), .D (n_360), .Q
       (master_tx_done));
  OR2XD1 g11026__1881(.A1 (n_375), .A2 (ctrl_state[0]), .Z (n_382));
  IND2D1 g11027__5115(.A1 (n_381), .B1 (ctrl_last_op_was_write), .ZN
       (n_379));
  CKND1 g11028(.I (n_385), .ZN (n_360));
  DFCNQD1 db_write_sync1_reg(.CDN (n_12), .CP (clk), .D
       (db_write_sync0), .Q (db_write_sync1));
  DFCNQD1 db_read_sync1_reg(.CDN (n_12), .CP (clk), .D (db_read_sync0),
       .Q (db_read_sync1));
  DFCNQD1 db_latch_sync1_reg(.CDN (n_12), .CP (clk), .D
       (db_latch_sync0), .Q (db_latch_sync1));
  OR2XD1 g11032__7482(.A1 (n_389), .A2 (n_391), .Z (n_377));
  IND2D1 g11033__4733(.A1 (n_386), .B1 (ctrl_state[1]), .ZN (n_375));
  CKND2D1 g11034__6161(.A1 (n_356), .A2 (spi_state[2]), .ZN (n_385));
  AN3XD1 g11035__9315(.A1 (timer_cnt[5]), .A2 (timer_cnt[2]), .A3
       (timer_cnt[1]), .Z (n_358));
  AN4XD1 g11036__9945(.A1 (timer_cnt[4]), .A2 (timer_cnt[7]), .A3
       (timer_cnt[6]), .A4 (timer_cnt[3]), .Z (n_357));
  OR2XD1 g11037__2883(.A1 (n_388), .A2 (n_380), .Z (n_359));
  OR2XD1 g11038__2346(.A1 (n_387), .A2 (n_390), .Z (n_383));
  OR2XD1 g11039__1666(.A1 (n_388), .A2 (n_386), .Z (n_381));
  OR2D1 g11040__7410(.A1 (n_386), .A2 (n_391), .Z (n_384));
  INVD1 g11041(.I (n_356), .ZN (n_392));
  DFCNQD1 db_read_sync0_reg(.CDN (n_12), .CP (clk), .D (btn[1]), .Q
       (db_read_sync0));
  DFCNQD1 db_write_sync0_reg(.CDN (n_12), .CP (clk), .D (btn[3]), .Q
       (db_write_sync0));
  DFCNQD1 db_latch_sync0_reg(.CDN (n_12), .CP (clk), .D (btn[2]), .Q
       (db_latch_sync0));
  NR2XD0 g11045__6417(.A1 (spi_state[0]), .A2 (spi_state[1]), .ZN
       (n_356));
  OR2D1 g11046__5477(.A1 (ctrl_state[3]), .A2 (ctrl_state[2]), .Z
       (n_389));
  IND2D1 g11047__2398(.A1 (ctrl_state[2]), .B1 (ctrl_state[3]), .ZN
       (n_390));
  IND2D1 g11048__5107(.A1 (ctrl_state[1]), .B1 (ctrl_state[0]), .ZN
       (n_387));
  ND2D1 g11049__6260(.A1 (ctrl_state[2]), .A2 (ctrl_state[3]), .ZN
       (n_380));
  OR2D1 g11050__4319(.A1 (ctrl_state[0]), .A2 (ctrl_state[1]), .Z
       (n_388));
  ND2D1 g11051__8428(.A1 (ctrl_state[1]), .A2 (ctrl_state[0]), .ZN
       (n_391));
  IND2D1 g11052__5526(.A1 (ctrl_state[3]), .B1 (ctrl_state[2]), .ZN
       (n_386));
  CKND1 g11053(.I (btn[0]), .ZN (n_12));
  SDFCNQD1 ctrl_btn_latch_db_reg(.CDN (n_12), .CP (clk), .D
       (ctrl_btn_latch_db), .SI (db_latch_sync1), .SE (n_295), .Q
       (ctrl_btn_latch_db));
  SDFCNQD1 ctrl_btn_read_s_db_reg(.CDN (n_12), .CP (clk), .D
       (ctrl_btn_read_s_db), .SI (db_read_sync1), .SE (n_296), .Q
       (ctrl_btn_read_s_db));
  SDFCNQD1 ctrl_btn_write_s_db_reg(.CDN (n_12), .CP (clk), .D
       (ctrl_btn_write_s_db), .SI (db_write_sync1), .SE (n_292), .Q
       (ctrl_btn_write_s_db));
  SDFCNQD1 \ctrl_gw_idx_reg[0] (.CDN (n_12), .CP (clk), .D (n_72), .SI
       (ctrl_gw_idx[0]), .SE (n_221), .Q (ctrl_gw_idx[0]));
  SDFCNQD1 \ctrl_gw_idx_reg[1] (.CDN (n_12), .CP (clk), .D (n_155), .SI
       (ctrl_gw_idx[1]), .SE (n_221), .Q (ctrl_gw_idx[1]));
  SDFCNQD1 \ctrl_gw_idx_reg[2] (.CDN (n_12), .CP (clk), .D (n_186), .SI
       (ctrl_gw_idx[2]), .SE (n_221), .Q (ctrl_gw_idx[2]));
  SDFCNQD1 ctrl_last_op_was_write_reg(.CDN (n_12), .CP (clk), .D
       (ctrl_last_op_was_write), .SI (ctrl_btn_write_s_db), .SE
       (n_149), .Q (ctrl_last_op_was_write));
  SDFCNQD1 \ctrl_latched_addr_reg[0] (.CDN (n_12), .CP (clk), .D
       (sw[0]), .SI (ctrl_latched_addr[0]), .SE (n_31), .Q
       (ctrl_latched_addr[0]));
  SDFCNQD1 \ctrl_latched_addr_reg[1] (.CDN (n_12), .CP (clk), .D
       (sw[1]), .SI (ctrl_latched_addr[1]), .SE (n_31), .Q
       (ctrl_latched_addr[1]));
  SDFCNQD1 \ctrl_latched_addr_reg[2] (.CDN (n_12), .CP (clk), .D
       (sw[2]), .SI (ctrl_latched_addr[2]), .SE (n_31), .Q
       (ctrl_latched_addr[2]));
  SDFCNQD1 \ctrl_latched_addr_reg[3] (.CDN (n_12), .CP (clk), .D
       (sw[3]), .SI (ctrl_latched_addr[3]), .SE (n_31), .Q
       (ctrl_latched_addr[3]));
  SDFCNQD1 \ctrl_latched_addr_reg[4] (.CDN (n_12), .CP (clk), .D
       (sw[4]), .SI (ctrl_latched_addr[4]), .SE (n_31), .Q
       (ctrl_latched_addr[4]));
  SDFCNQD1 \ctrl_latched_addr_reg[5] (.CDN (n_12), .CP (clk), .D
       (sw[5]), .SI (ctrl_latched_addr[5]), .SE (n_31), .Q
       (ctrl_latched_addr[5]));
  SDFCNQD1 \ctrl_latched_addr_reg[6] (.CDN (n_12), .CP (clk), .D
       (sw[6]), .SI (ctrl_latched_addr[6]), .SE (n_31), .Q
       (ctrl_latched_addr[6]));
  SDFCNQD1 \ctrl_latched_addr_reg[7] (.CDN (n_12), .CP (clk), .D
       (sw[7]), .SI (ctrl_latched_addr[7]), .SE (n_31), .Q
       (ctrl_latched_addr[7]));
  SDFCNQD1 ctrl_latched_global_reg(.CDN (n_12), .CP (clk), .D (sw[15]),
       .SI (ctrl_latched_global), .SE (n_31), .Q (ctrl_latched_global));
  SDFCNQD1 \ctrl_latched_id_reg[0] (.CDN (n_12), .CP (clk), .D (sw[8]),
       .SI (ctrl_latched_id[0]), .SE (n_31), .Q (ctrl_latched_id[0]));
  SDFCNQD1 \ctrl_latched_id_reg[1] (.CDN (n_12), .CP (clk), .D (sw[9]),
       .SI (ctrl_latched_id[1]), .SE (n_31), .Q (ctrl_latched_id[1]));
  SDFCNQD1 \ctrl_latched_id_reg[2] (.CDN (n_12), .CP (clk), .D
       (sw[10]), .SI (ctrl_latched_id[2]), .SE (n_31), .Q
       (ctrl_latched_id[2]));
  SDFCNQD1 \ctrl_latched_write_data_reg[0] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[0]), .SI (sw[0]), .SE (n_137), .Q
       (ctrl_latched_write_data[0]));
  SDFCNQD1 \ctrl_latched_write_data_reg[1] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[1]), .SI (sw[1]), .SE (n_137), .Q
       (ctrl_latched_write_data[1]));
  SDFCNQD1 \ctrl_latched_write_data_reg[2] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[2]), .SI (sw[2]), .SE (n_137), .Q
       (ctrl_latched_write_data[2]));
  SDFCNQD1 \ctrl_latched_write_data_reg[3] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[3]), .SI (sw[3]), .SE (n_137), .Q
       (ctrl_latched_write_data[3]));
  SDFCNQD1 \ctrl_latched_write_data_reg[4] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[4]), .SI (sw[4]), .SE (n_137), .Q
       (ctrl_latched_write_data[4]));
  SDFCNQD1 \ctrl_latched_write_data_reg[5] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[5]), .SI (sw[5]), .SE (n_137), .Q
       (ctrl_latched_write_data[5]));
  SDFCNQD1 \ctrl_latched_write_data_reg[6] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[6]), .SI (sw[6]), .SE (n_137), .Q
       (ctrl_latched_write_data[6]));
  SDFCNQD1 \ctrl_latched_write_data_reg[7] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[7]), .SI (sw[7]), .SE (n_137), .Q
       (ctrl_latched_write_data[7]));
  SDFCNQD1 \ctrl_latched_write_data_reg[8] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[8]), .SI (sw[8]), .SE (n_137), .Q
       (ctrl_latched_write_data[8]));
  SDFCNQD1 \ctrl_latched_write_data_reg[9] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[9]), .SI (sw[9]), .SE (n_137), .Q
       (ctrl_latched_write_data[9]));
  SDFCNQD1 \ctrl_latched_write_data_reg[10] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[10]), .SI (sw[10]), .SE (n_137), .Q
       (ctrl_latched_write_data[10]));
  SDFCNQD1 \ctrl_latched_write_data_reg[11] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[11]), .SI (sw[11]), .SE (n_137), .Q
       (ctrl_latched_write_data[11]));
  SDFCNQD1 \ctrl_latched_write_data_reg[12] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[12]), .SI (sw[12]), .SE (n_137), .Q
       (ctrl_latched_write_data[12]));
  SDFCNQD1 \ctrl_latched_write_data_reg[13] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[13]), .SI (sw[13]), .SE (n_137), .Q
       (ctrl_latched_write_data[13]));
  SDFCNQD1 \ctrl_latched_write_data_reg[14] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[14]), .SI (sw[14]), .SE (n_137), .Q
       (ctrl_latched_write_data[14]));
  SDFCNQD1 \ctrl_latched_write_data_reg[15] (.CDN (n_12), .CP (clk), .D
       (ctrl_latched_write_data[15]), .SI (sw[15]), .SE (n_137), .Q
       (ctrl_latched_write_data[15]));
  SDFCNQD1 \ctrl_state_reg[0] (.CDN (n_12), .CP (clk), .D (n_216), .SI
       (ctrl_state[0]), .SE (n_288), .Q (ctrl_state[0]));
  DFCNQD1 \ctrl_state_reg[1] (.CDN (n_12), .CP (clk), .D (n_293), .Q
       (ctrl_state[1]));
  SDFCNQD1 \ctrl_state_reg[2] (.CDN (n_12), .CP (clk), .D (n_241), .SI
       (ctrl_state[2]), .SE (n_288), .Q (ctrl_state[2]));
  DFCNQD1 \ctrl_state_reg[3] (.CDN (n_12), .CP (clk), .D (n_233), .Q
       (ctrl_state[3]));
  DFCNQD1 \db_latch_cnt_reg[0] (.CDN (n_12), .CP (clk), .D (n_350), .Q
       (db_latch_cnt[0]));
  DFCNQD1 \db_latch_cnt_reg[1] (.CDN (n_12), .CP (clk), .D (n_349), .Q
       (db_latch_cnt[1]));
  DFCNQD1 \db_latch_cnt_reg[2] (.CDN (n_12), .CP (clk), .D (n_348), .Q
       (db_latch_cnt[2]));
  DFCNQD1 \db_latch_cnt_reg[3] (.CDN (n_12), .CP (clk), .D (n_347), .Q
       (db_latch_cnt[3]));
  DFCNQD1 \db_latch_cnt_reg[4] (.CDN (n_12), .CP (clk), .D (n_346), .Q
       (db_latch_cnt[4]));
  DFCNQD1 \db_latch_cnt_reg[5] (.CDN (n_12), .CP (clk), .D (n_345), .Q
       (db_latch_cnt[5]));
  DFCNQD1 \db_latch_cnt_reg[6] (.CDN (n_12), .CP (clk), .D (n_342), .Q
       (db_latch_cnt[6]));
  DFCNQD1 \db_latch_cnt_reg[7] (.CDN (n_12), .CP (clk), .D (n_344), .Q
       (db_latch_cnt[7]));
  DFCNQD1 \db_latch_cnt_reg[8] (.CDN (n_12), .CP (clk), .D (n_343), .Q
       (db_latch_cnt[8]));
  DFCNQD1 \db_latch_cnt_reg[9] (.CDN (n_12), .CP (clk), .D (n_341), .Q
       (db_latch_cnt[9]));
  DFCNQD1 \db_latch_cnt_reg[10] (.CDN (n_12), .CP (clk), .D (n_340), .Q
       (db_latch_cnt[10]));
  DFCNQD1 \db_latch_cnt_reg[11] (.CDN (n_12), .CP (clk), .D (n_339), .Q
       (db_latch_cnt[11]));
  DFCNQD1 \db_latch_cnt_reg[12] (.CDN (n_12), .CP (clk), .D (n_338), .Q
       (db_latch_cnt[12]));
  DFCNQD1 \db_latch_cnt_reg[13] (.CDN (n_12), .CP (clk), .D (n_337), .Q
       (db_latch_cnt[13]));
  DFCNQD1 \db_latch_cnt_reg[14] (.CDN (n_12), .CP (clk), .D (n_336), .Q
       (db_latch_cnt[14]));
  DFCNQD1 \db_latch_cnt_reg[15] (.CDN (n_12), .CP (clk), .D (n_335), .Q
       (db_latch_cnt[15]));
  DFCNQD1 \db_latch_cnt_reg[16] (.CDN (n_12), .CP (clk), .D (n_334), .Q
       (db_latch_cnt[16]));
  DFCNQD1 \db_latch_cnt_reg[17] (.CDN (n_12), .CP (clk), .D (n_333), .Q
       (db_latch_cnt[17]));
  DFCNQD1 \db_read_cnt_reg[0] (.CDN (n_12), .CP (clk), .D (n_331), .Q
       (db_read_cnt[0]));
  DFCNQD1 \db_read_cnt_reg[1] (.CDN (n_12), .CP (clk), .D (n_330), .Q
       (db_read_cnt[1]));
  DFCNQD1 \db_read_cnt_reg[2] (.CDN (n_12), .CP (clk), .D (n_329), .Q
       (db_read_cnt[2]));
  DFCNQD1 \db_read_cnt_reg[3] (.CDN (n_12), .CP (clk), .D (n_328), .Q
       (db_read_cnt[3]));
  DFCNQD1 \db_read_cnt_reg[4] (.CDN (n_12), .CP (clk), .D (n_327), .Q
       (db_read_cnt[4]));
  DFCNQD1 \db_read_cnt_reg[5] (.CDN (n_12), .CP (clk), .D (n_351), .Q
       (db_read_cnt[5]));
  DFCNQD1 \db_read_cnt_reg[6] (.CDN (n_12), .CP (clk), .D (n_352), .Q
       (db_read_cnt[6]));
  DFCNQD1 \db_read_cnt_reg[7] (.CDN (n_12), .CP (clk), .D (n_353), .Q
       (db_read_cnt[7]));
  DFCNQD1 \db_read_cnt_reg[8] (.CDN (n_12), .CP (clk), .D (n_297), .Q
       (db_read_cnt[8]));
  DFCNQD1 \db_read_cnt_reg[9] (.CDN (n_12), .CP (clk), .D (n_325), .Q
       (db_read_cnt[9]));
  DFCNQD1 \db_read_cnt_reg[10] (.CDN (n_12), .CP (clk), .D (n_324), .Q
       (db_read_cnt[10]));
  DFCNQD1 \db_read_cnt_reg[11] (.CDN (n_12), .CP (clk), .D (n_323), .Q
       (db_read_cnt[11]));
  DFCNQD1 \db_read_cnt_reg[12] (.CDN (n_12), .CP (clk), .D (n_322), .Q
       (db_read_cnt[12]));
  DFCNQD1 \db_read_cnt_reg[13] (.CDN (n_12), .CP (clk), .D (n_321), .Q
       (db_read_cnt[13]));
  DFCNQD1 \db_read_cnt_reg[14] (.CDN (n_12), .CP (clk), .D (n_320), .Q
       (db_read_cnt[14]));
  DFCNQD1 \db_read_cnt_reg[15] (.CDN (n_12), .CP (clk), .D (n_319), .Q
       (db_read_cnt[15]));
  DFCNQD1 \db_read_cnt_reg[16] (.CDN (n_12), .CP (clk), .D (n_318), .Q
       (db_read_cnt[16]));
  DFCNQD1 \db_read_cnt_reg[17] (.CDN (n_12), .CP (clk), .D (n_317), .Q
       (db_read_cnt[17]));
  DFCNQD1 \db_write_cnt_reg[0] (.CDN (n_12), .CP (clk), .D (n_314), .Q
       (db_write_cnt[0]));
  DFCNQD1 \db_write_cnt_reg[1] (.CDN (n_12), .CP (clk), .D (n_315), .Q
       (db_write_cnt[1]));
  DFCNQD1 \db_write_cnt_reg[2] (.CDN (n_12), .CP (clk), .D (n_313), .Q
       (db_write_cnt[2]));
  DFCNQD1 \db_write_cnt_reg[3] (.CDN (n_12), .CP (clk), .D (n_312), .Q
       (db_write_cnt[3]));
  DFCNQD1 \db_write_cnt_reg[4] (.CDN (n_12), .CP (clk), .D (n_311), .Q
       (db_write_cnt[4]));
  DFCNQD1 \db_write_cnt_reg[5] (.CDN (n_12), .CP (clk), .D (n_310), .Q
       (db_write_cnt[5]));
  DFCNQD1 \db_write_cnt_reg[6] (.CDN (n_12), .CP (clk), .D (n_309), .Q
       (db_write_cnt[6]));
  DFCNQD1 \db_write_cnt_reg[7] (.CDN (n_12), .CP (clk), .D (n_308), .Q
       (db_write_cnt[7]));
  DFCNQD1 \db_write_cnt_reg[8] (.CDN (n_12), .CP (clk), .D (n_307), .Q
       (db_write_cnt[8]));
  DFCNQD1 \db_write_cnt_reg[9] (.CDN (n_12), .CP (clk), .D (n_306), .Q
       (db_write_cnt[9]));
  DFCNQD1 \db_write_cnt_reg[10] (.CDN (n_12), .CP (clk), .D (n_305), .Q
       (db_write_cnt[10]));
  DFCNQD1 \db_write_cnt_reg[11] (.CDN (n_12), .CP (clk), .D (n_304), .Q
       (db_write_cnt[11]));
  DFCNQD1 \db_write_cnt_reg[12] (.CDN (n_12), .CP (clk), .D (n_303), .Q
       (db_write_cnt[12]));
  DFCNQD1 \db_write_cnt_reg[13] (.CDN (n_12), .CP (clk), .D (n_302), .Q
       (db_write_cnt[13]));
  DFCNQD1 \db_write_cnt_reg[14] (.CDN (n_12), .CP (clk), .D (n_301), .Q
       (db_write_cnt[14]));
  DFCNQD1 \db_write_cnt_reg[15] (.CDN (n_12), .CP (clk), .D (n_298), .Q
       (db_write_cnt[15]));
  DFCNQD1 \db_write_cnt_reg[16] (.CDN (n_12), .CP (clk), .D (n_300), .Q
       (db_write_cnt[16]));
  DFCNQD1 \db_write_cnt_reg[17] (.CDN (n_12), .CP (clk), .D (n_299), .Q
       (db_write_cnt[17]));
  SDFCNQD2 led_blue_wire_reg(.CDN (n_12), .CP (clk), .D (RGB0[2]), .SI
       (n_18), .SE (n_150), .Q (RGB0[2]));
  SDFCNQD2 led_green_wire_reg(.CDN (n_12), .CP (clk), .D (RGB0[1]), .SI
       (n_294), .SE (n_30), .Q (RGB0[1]));
  SDFCNQD2 led_red_wire_reg(.CDN (n_12), .CP (clk), .D (n_354), .SI
       (RGB0[0]), .SE (n_94), .Q (RGB0[0]));
  SDFCNQD2 \led_reg[0] (.CDN (n_12), .CP (clk), .D (led[0]), .SI
       (master_data_rd[0]), .SE (n_30), .Q (led[0]));
  SDFCNQD2 \led_reg[1] (.CDN (n_12), .CP (clk), .D (led[1]), .SI
       (master_data_rd[1]), .SE (n_30), .Q (led[1]));
  SDFCNQD2 \led_reg[2] (.CDN (n_12), .CP (clk), .D (led[2]), .SI
       (master_data_rd[2]), .SE (n_30), .Q (led[2]));
  SDFCNQD2 \led_reg[3] (.CDN (n_12), .CP (clk), .D (led[3]), .SI
       (master_data_rd[3]), .SE (n_30), .Q (led[3]));
  SDFCNQD2 \led_reg[4] (.CDN (n_12), .CP (clk), .D (led[4]), .SI
       (master_data_rd[4]), .SE (n_30), .Q (led[4]));
  SDFCNQD2 \led_reg[5] (.CDN (n_12), .CP (clk), .D (led[5]), .SI
       (master_data_rd[5]), .SE (n_30), .Q (led[5]));
  SDFCNQD2 \led_reg[6] (.CDN (n_12), .CP (clk), .D (led[6]), .SI
       (master_data_rd[6]), .SE (n_30), .Q (led[6]));
  SDFCNQD2 \led_reg[7] (.CDN (n_12), .CP (clk), .D (led[7]), .SI
       (master_data_rd[7]), .SE (n_30), .Q (led[7]));
  SDFCNQD2 \led_reg[8] (.CDN (n_12), .CP (clk), .D (led[8]), .SI
       (master_data_rd[8]), .SE (n_30), .Q (led[8]));
  SDFCNQD2 \led_reg[9] (.CDN (n_12), .CP (clk), .D (led[9]), .SI
       (master_data_rd[9]), .SE (n_30), .Q (led[9]));
  SDFCNQD2 \led_reg[10] (.CDN (n_12), .CP (clk), .D (led[10]), .SI
       (master_data_rd[10]), .SE (n_30), .Q (led[10]));
  SDFCNQD2 \led_reg[11] (.CDN (n_12), .CP (clk), .D (led[11]), .SI
       (master_data_rd[11]), .SE (n_30), .Q (led[11]));
  SDFCNQD2 \led_reg[12] (.CDN (n_12), .CP (clk), .D (led[12]), .SI
       (master_data_rd[12]), .SE (n_30), .Q (led[12]));
  SDFCNQD2 \led_reg[13] (.CDN (n_12), .CP (clk), .D (led[13]), .SI
       (master_data_rd[13]), .SE (n_30), .Q (led[13]));
  SDFCNQD2 \led_reg[14] (.CDN (n_12), .CP (clk), .D (led[14]), .SI
       (master_data_rd[14]), .SE (n_30), .Q (led[14]));
  SDFCNQD2 \led_reg[15] (.CDN (n_12), .CP (clk), .D (led[15]), .SI
       (master_data_rd[15]), .SE (n_30), .Q (led[15]));
  SDFCNQD1 \master_cmd_packet_reg[2] (.CDN (n_12), .CP (clk), .D
       (master_cmd_packet[2]), .SI (n_33), .SE (n_220), .Q
       (master_cmd_packet[2]));
  SDFCNQD1 \master_cmd_packet_reg[3] (.CDN (n_12), .CP (clk), .D
       (master_cmd_packet[3]), .SI (ctrl_latched_addr[0]), .SE (n_220),
       .Q (master_cmd_packet[3]));
  SDFCNQD1 \master_cmd_packet_reg[4] (.CDN (n_12), .CP (clk), .D
       (master_cmd_packet[4]), .SI (ctrl_latched_addr[1]), .SE (n_220),
       .Q (master_cmd_packet[4]));
  SDFCNQD1 \master_cmd_packet_reg[5] (.CDN (n_12), .CP (clk), .D
       (master_cmd_packet[5]), .SI (ctrl_latched_addr[2]), .SE (n_220),
       .Q (master_cmd_packet[5]));
  SDFCNQD1 \master_cmd_packet_reg[6] (.CDN (n_12), .CP (clk), .D
       (master_cmd_packet[6]), .SI (ctrl_latched_addr[3]), .SE (n_220),
       .Q (master_cmd_packet[6]));
  SDFCNQD1 \master_cmd_packet_reg[7] (.CDN (n_12), .CP (clk), .D
       (master_cmd_packet[7]), .SI (ctrl_latched_addr[4]), .SE (n_220),
       .Q (master_cmd_packet[7]));
  SDFCNQD1 \master_cmd_packet_reg[8] (.CDN (n_12), .CP (clk), .D
       (master_cmd_packet[8]), .SI (ctrl_latched_addr[5]), .SE (n_220),
       .Q (master_cmd_packet[8]));
  SDFCNQD1 \master_cmd_packet_reg[9] (.CDN (n_12), .CP (clk), .D
       (master_cmd_packet[9]), .SI (ctrl_latched_addr[6]), .SE (n_220),
       .Q (master_cmd_packet[9]));
  SDFCNQD1 \master_cmd_packet_reg[10] (.CDN (n_12), .CP (clk), .D
       (master_cmd_packet[10]), .SI (ctrl_latched_addr[7]), .SE
       (n_220), .Q (master_cmd_packet[10]));
  SDFCNQD1 \master_cmd_packet_reg[11] (.CDN (n_12), .CP (clk), .D
       (master_cmd_packet[11]), .SI (n_95), .SE (n_220), .Q
       (master_cmd_packet[11]));
  SDFCNQD1 \master_cmd_packet_reg[12] (.CDN (n_12), .CP (clk), .D
       (master_cmd_packet[12]), .SI (n_98), .SE (n_220), .Q
       (master_cmd_packet[12]));
  SDFCNQD1 \master_cmd_packet_reg[13] (.CDN (n_12), .CP (clk), .D
       (master_cmd_packet[13]), .SI (n_100), .SE (n_220), .Q
       (master_cmd_packet[13]));
  SDFCNQD1 \master_data_rd_reg[0] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[0]), .SI (spi_shifter_in[0]), .SE (n_21), .Q
       (master_data_rd[0]));
  SDFCNQD1 \master_data_rd_reg[1] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[1]), .SI (spi_shifter_in[1]), .SE (n_21), .Q
       (master_data_rd[1]));
  SDFCNQD1 \master_data_rd_reg[2] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[2]), .SI (spi_shifter_in[2]), .SE (n_21), .Q
       (master_data_rd[2]));
  SDFCNQD1 \master_data_rd_reg[3] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[3]), .SI (spi_shifter_in[3]), .SE (n_21), .Q
       (master_data_rd[3]));
  SDFCNQD1 \master_data_rd_reg[4] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[4]), .SI (spi_shifter_in[4]), .SE (n_21), .Q
       (master_data_rd[4]));
  SDFCNQD1 \master_data_rd_reg[5] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[5]), .SI (spi_shifter_in[5]), .SE (n_21), .Q
       (master_data_rd[5]));
  SDFCNQD1 \master_data_rd_reg[6] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[6]), .SI (spi_shifter_in[6]), .SE (n_21), .Q
       (master_data_rd[6]));
  SDFCNQD1 \master_data_rd_reg[7] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[7]), .SI (spi_shifter_in[7]), .SE (n_21), .Q
       (master_data_rd[7]));
  SDFCNQD1 \master_data_rd_reg[8] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[8]), .SI (spi_shifter_in[8]), .SE (n_21), .Q
       (master_data_rd[8]));
  SDFCNQD1 \master_data_rd_reg[9] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[9]), .SI (spi_shifter_in[9]), .SE (n_21), .Q
       (master_data_rd[9]));
  SDFCNQD1 \master_data_rd_reg[10] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[10]), .SI (spi_shifter_in[10]), .SE (n_21), .Q
       (master_data_rd[10]));
  SDFCNQD1 \master_data_rd_reg[11] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[11]), .SI (spi_shifter_in[11]), .SE (n_21), .Q
       (master_data_rd[11]));
  SDFCNQD1 \master_data_rd_reg[12] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[12]), .SI (spi_shifter_in[12]), .SE (n_21), .Q
       (master_data_rd[12]));
  SDFCNQD1 \master_data_rd_reg[13] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[13]), .SI (spi_shifter_in[13]), .SE (n_21), .Q
       (master_data_rd[13]));
  SDFCNQD1 \master_data_rd_reg[14] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[14]), .SI (spi_shifter_in[14]), .SE (n_21), .Q
       (master_data_rd[14]));
  SDFCNQD1 \master_data_rd_reg[15] (.CDN (n_12), .CP (clk), .D
       (master_data_rd[15]), .SI (spi_shifter_in[15]), .SE (n_21), .Q
       (master_data_rd[15]));
  SDFCNQD1 \master_data_wr_reg[0] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[0]), .SI (n_161), .SE (n_220), .Q
       (master_data_wr[0]));
  SDFCNQD1 \master_data_wr_reg[1] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[1]), .SI (n_162), .SE (n_220), .Q
       (master_data_wr[1]));
  SDFCNQD1 \master_data_wr_reg[2] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[2]), .SI (n_163), .SE (n_220), .Q
       (master_data_wr[2]));
  SDFCNQD1 \master_data_wr_reg[3] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[3]), .SI (n_164), .SE (n_220), .Q
       (master_data_wr[3]));
  SDFCNQD1 \master_data_wr_reg[4] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[4]), .SI (n_165), .SE (n_220), .Q
       (master_data_wr[4]));
  SDFCNQD1 \master_data_wr_reg[5] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[5]), .SI (n_166), .SE (n_220), .Q
       (master_data_wr[5]));
  SDFCNQD1 \master_data_wr_reg[6] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[6]), .SI (n_167), .SE (n_220), .Q
       (master_data_wr[6]));
  SDFCNQD1 \master_data_wr_reg[7] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[7]), .SI (n_168), .SE (n_220), .Q
       (master_data_wr[7]));
  SDFCNQD1 \master_data_wr_reg[8] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[8]), .SI (n_160), .SE (n_220), .Q
       (master_data_wr[8]));
  SDFCNQD1 \master_data_wr_reg[9] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[9]), .SI (n_153), .SE (n_220), .Q
       (master_data_wr[9]));
  SDFCNQD1 \master_data_wr_reg[10] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[10]), .SI (n_152), .SE (n_220), .Q
       (master_data_wr[10]));
  SDFCNQD1 \master_data_wr_reg[11] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[11]), .SI (n_151), .SE (n_220), .Q
       (master_data_wr[11]));
  SDFCNQD1 \master_data_wr_reg[12] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[12]), .SI (n_157), .SE (n_220), .Q
       (master_data_wr[12]));
  SDFCNQD1 \master_data_wr_reg[13] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[13]), .SI (n_158), .SE (n_220), .Q
       (master_data_wr[13]));
  SDFCNQD1 \master_data_wr_reg[14] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[14]), .SI (n_159), .SE (n_220), .Q
       (master_data_wr[14]));
  SDFCNQD1 \master_data_wr_reg[15] (.CDN (n_12), .CP (clk), .D
       (master_data_wr[15]), .SI (n_169), .SE (n_220), .Q
       (master_data_wr[15]));
  SDFCNQD1 master_spi_busy_reg(.CDN (n_12), .CP (clk), .D (n_83), .SI
       (master_spi_busy), .SE (n_392), .Q (master_spi_busy));
  DFCNQD1 spi_active_reg(.CDN (n_12), .CP (clk), .D (n_252), .Q
       (spi_active));
  SDFCNQD1 \spi_bitcnt_reg[0] (.CDN (n_12), .CP (clk), .D (n_200), .SI
       (n_224), .SE (spi_bitcnt[0]), .Q (spi_bitcnt[0]));
  DFCNQD1 \spi_bitcnt_reg[1] (.CDN (n_12), .CP (clk), .D (n_263), .Q
       (spi_bitcnt[1]));
  DFCNQD1 \spi_bitcnt_reg[2] (.CDN (n_12), .CP (clk), .D (n_264), .Q
       (spi_bitcnt[2]));
  DFCNQD1 \spi_bitcnt_reg[3] (.CDN (n_12), .CP (clk), .D (n_265), .Q
       (spi_bitcnt[3]));
  DFCNQD1 \spi_bitcnt_reg[4] (.CDN (n_12), .CP (clk), .D (n_243), .Q
       (spi_bitcnt[4]));
  SDFSNQD2 \spi_cs_n_out_reg[0] (.SDN (n_12), .CP (clk), .D (n_195),
       .SI (spi_cs_n_out[0]), .SE (n_236), .Q (spi_cs_n_out[0]));
  SDFSNQD2 \spi_cs_n_out_reg[1] (.SDN (n_12), .CP (clk), .D (n_191),
       .SI (spi_cs_n_out[1]), .SE (n_236), .Q (spi_cs_n_out[1]));
  SDFSNQD2 \spi_cs_n_out_reg[2] (.SDN (n_12), .CP (clk), .D (n_193),
       .SI (spi_cs_n_out[2]), .SE (n_236), .Q (spi_cs_n_out[2]));
  SDFSNQD2 \spi_cs_n_out_reg[3] (.SDN (n_12), .CP (clk), .D (n_198),
       .SI (spi_cs_n_out[3]), .SE (n_236), .Q (spi_cs_n_out[3]));
  SDFSNQD2 \spi_cs_n_out_reg[4] (.SDN (n_12), .CP (clk), .D (n_197),
       .SI (spi_cs_n_out[4]), .SE (n_236), .Q (spi_cs_n_out[4]));
  SDFSNQD2 \spi_cs_n_out_reg[5] (.SDN (n_12), .CP (clk), .D (n_194),
       .SI (spi_cs_n_out[5]), .SE (n_236), .Q (spi_cs_n_out[5]));
  SDFSNQD2 \spi_cs_n_out_reg[6] (.SDN (n_12), .CP (clk), .D (n_196),
       .SI (spi_cs_n_out[6]), .SE (n_236), .Q (spi_cs_n_out[6]));
  SDFSNQD2 \spi_cs_n_out_reg[7] (.SDN (n_12), .CP (clk), .D (n_192),
       .SI (spi_cs_n_out[7]), .SE (n_236), .Q (spi_cs_n_out[7]));
  DFSNQD1 \spi_divcnt_reg[0] (.SDN (n_12), .CP (clk), .D (n_156), .Q
       (spi_divcnt[0]));
  DFSNQD1 \spi_divcnt_reg[1] (.SDN (n_12), .CP (clk), .D (n_183), .Q
       (spi_divcnt[1]));
  SDFCNQD2 spi_mosi_out_reg(.CDN (n_12), .CP (clk), .D (spi_mosi_out),
       .SI (n_242), .SE (n_201), .Q (spi_mosi_out));
  DFCNQD2 spi_sclk_out_reg(.CDN (n_12), .CP (clk), .D (n_181), .Q
       (spi_sclk_out));
  DFCNQD1 \spi_shifter_in_reg[0] (.CDN (n_12), .CP (clk), .D (n_259),
       .Q (spi_shifter_in[0]));
  DFCNQD1 \spi_shifter_in_reg[1] (.CDN (n_12), .CP (clk), .D (n_258),
       .Q (spi_shifter_in[1]));
  DFCNQD1 \spi_shifter_in_reg[2] (.CDN (n_12), .CP (clk), .D (n_257),
       .Q (spi_shifter_in[2]));
  DFCNQD1 \spi_shifter_in_reg[3] (.CDN (n_12), .CP (clk), .D (n_256),
       .Q (spi_shifter_in[3]));
  DFCNQD1 \spi_shifter_in_reg[4] (.CDN (n_12), .CP (clk), .D (n_255),
       .Q (spi_shifter_in[4]));
  DFCNQD1 \spi_shifter_in_reg[5] (.CDN (n_12), .CP (clk), .D (n_254),
       .Q (spi_shifter_in[5]));
  DFCNQD1 \spi_shifter_in_reg[6] (.CDN (n_12), .CP (clk), .D (n_253),
       .Q (spi_shifter_in[6]));
  DFCNQD1 \spi_shifter_in_reg[7] (.CDN (n_12), .CP (clk), .D (n_266),
       .Q (spi_shifter_in[7]));
  DFCNQD1 \spi_shifter_in_reg[8] (.CDN (n_12), .CP (clk), .D (n_251),
       .Q (spi_shifter_in[8]));
  DFCNQD1 \spi_shifter_in_reg[9] (.CDN (n_12), .CP (clk), .D (n_250),
       .Q (spi_shifter_in[9]));
  DFCNQD1 \spi_shifter_in_reg[10] (.CDN (n_12), .CP (clk), .D (n_249),
       .Q (spi_shifter_in[10]));
  DFCNQD1 \spi_shifter_in_reg[11] (.CDN (n_12), .CP (clk), .D (n_248),
       .Q (spi_shifter_in[11]));
  DFCNQD1 \spi_shifter_in_reg[12] (.CDN (n_12), .CP (clk), .D (n_247),
       .Q (spi_shifter_in[12]));
  DFCNQD1 \spi_shifter_in_reg[13] (.CDN (n_12), .CP (clk), .D (n_246),
       .Q (spi_shifter_in[13]));
  DFCNQD1 \spi_shifter_in_reg[14] (.CDN (n_12), .CP (clk), .D (n_245),
       .Q (spi_shifter_in[14]));
  DFCNQD1 \spi_shifter_in_reg[15] (.CDN (n_12), .CP (clk), .D (n_244),
       .Q (spi_shifter_in[15]));
  DFCNQD1 \spi_shifter_out_reg[0] (.CDN (n_12), .CP (clk), .D (n_285),
       .Q (spi_shifter_out[0]));
  SDFCNQD1 \spi_shifter_out_reg[1] (.CDN (n_12), .CP (clk), .D
       (spi_shifter_out[1]), .SI (n_214), .SE (n_269), .Q
       (spi_shifter_out[1]));
  DFCNQD1 \spi_shifter_out_reg[2] (.CDN (n_12), .CP (clk), .D (n_284),
       .Q (spi_shifter_out[2]));
  DFCNQD1 \spi_shifter_out_reg[3] (.CDN (n_12), .CP (clk), .D (n_283),
       .Q (spi_shifter_out[3]));
  DFCNQD1 \spi_shifter_out_reg[4] (.CDN (n_12), .CP (clk), .D (n_282),
       .Q (spi_shifter_out[4]));
  DFCNQD1 \spi_shifter_out_reg[5] (.CDN (n_12), .CP (clk), .D (n_287),
       .Q (spi_shifter_out[5]));
  DFCNQD1 \spi_shifter_out_reg[6] (.CDN (n_12), .CP (clk), .D (n_277),
       .Q (spi_shifter_out[6]));
  DFCNQD1 \spi_shifter_out_reg[7] (.CDN (n_12), .CP (clk), .D (n_280),
       .Q (spi_shifter_out[7]));
  DFCNQD1 \spi_shifter_out_reg[8] (.CDN (n_12), .CP (clk), .D (n_279),
       .Q (spi_shifter_out[8]));
  DFCNQD1 \spi_shifter_out_reg[9] (.CDN (n_12), .CP (clk), .D (n_278),
       .Q (spi_shifter_out[9]));
  DFCNQD1 \spi_shifter_out_reg[10] (.CDN (n_12), .CP (clk), .D (n_281),
       .Q (spi_shifter_out[10]));
  DFCNQD1 \spi_shifter_out_reg[11] (.CDN (n_12), .CP (clk), .D (n_276),
       .Q (spi_shifter_out[11]));
  DFCNQD1 \spi_shifter_out_reg[12] (.CDN (n_12), .CP (clk), .D (n_275),
       .Q (spi_shifter_out[12]));
  DFCNQD1 \spi_shifter_out_reg[13] (.CDN (n_12), .CP (clk), .D (n_274),
       .Q (spi_shifter_out[13]));
  SDFCNQD1 \spi_shifter_out_reg[14] (.CDN (n_12), .CP (clk), .D
       (spi_shifter_out[14]), .SI (n_179), .SE (n_269), .Q
       (spi_shifter_out[14]));
  SDFCNQD1 \spi_shifter_out_reg[15] (.CDN (n_12), .CP (clk), .D
       (spi_shifter_out[15]), .SI (n_185), .SE (n_269), .Q
       (spi_shifter_out[15]));
  SDFCNQD1 \spi_state_reg[0] (.CDN (n_12), .CP (clk), .D
       (spi_state[0]), .SI (n_4), .SE (n_273), .Q (spi_state[0]));
  SDFCNQD1 \spi_state_reg[1] (.CDN (n_12), .CP (clk), .D
       (spi_state[1]), .SI (n_124), .SE (n_273), .Q (spi_state[1]));
  SDFCNQD1 \spi_state_reg[2] (.CDN (n_12), .CP (clk), .D
       (spi_state[2]), .SI (n_80), .SE (n_273), .Q (spi_state[2]));
  DFCNQD1 \timer_cnt_reg[0] (.CDN (n_12), .CP (clk), .D (n_99), .Q
       (timer_cnt[0]));
  DFCNQD1 \timer_cnt_reg[1] (.CDN (n_12), .CP (clk), .D (n_125), .Q
       (timer_cnt[1]));
  DFCNQD1 \timer_cnt_reg[2] (.CDN (n_12), .CP (clk), .D (n_127), .Q
       (timer_cnt[2]));
  DFCNQD1 \timer_cnt_reg[3] (.CDN (n_12), .CP (clk), .D (n_128), .Q
       (timer_cnt[3]));
  DFCNQD1 \timer_cnt_reg[4] (.CDN (n_12), .CP (clk), .D (n_129), .Q
       (timer_cnt[4]));
  DFCNQD1 \timer_cnt_reg[5] (.CDN (n_12), .CP (clk), .D (n_130), .Q
       (timer_cnt[5]));
  DFCNQD1 \timer_cnt_reg[6] (.CDN (n_12), .CP (clk), .D (n_131), .Q
       (timer_cnt[6]));
  DFCNQD1 \timer_cnt_reg[7] (.CDN (n_12), .CP (clk), .D (n_132), .Q
       (timer_cnt[7]));
  DFCNQD1 \timer_cnt_reg[8] (.CDN (n_12), .CP (clk), .D (n_133), .Q
       (timer_cnt[8]));
  DFCNQD1 \timer_cnt_reg[9] (.CDN (n_12), .CP (clk), .D (n_134), .Q
       (timer_cnt[9]));
  DFCNQD1 \timer_cnt_reg[10] (.CDN (n_12), .CP (clk), .D (n_118), .Q
       (timer_cnt[10]));
  DFCNQD1 \timer_cnt_reg[11] (.CDN (n_12), .CP (clk), .D (n_117), .Q
       (timer_cnt[11]));
  DFCNQD1 \timer_cnt_reg[12] (.CDN (n_12), .CP (clk), .D (n_116), .Q
       (timer_cnt[12]));
  DFCNQD1 \timer_cnt_reg[13] (.CDN (n_12), .CP (clk), .D (n_115), .Q
       (timer_cnt[13]));
  DFCNQD1 \timer_cnt_reg[14] (.CDN (n_12), .CP (clk), .D (n_114), .Q
       (timer_cnt[14]));
  DFCNQD1 \timer_cnt_reg[15] (.CDN (n_12), .CP (clk), .D (n_113), .Q
       (timer_cnt[15]));
  DFCNQD1 \timer_cnt_reg[16] (.CDN (n_12), .CP (clk), .D (n_112), .Q
       (timer_cnt[16]));
  DFCNQD1 \timer_cnt_reg[17] (.CDN (n_12), .CP (clk), .D (n_111), .Q
       (timer_cnt[17]));
  DFCNQD1 \timer_cnt_reg[18] (.CDN (n_12), .CP (clk), .D (n_110), .Q
       (timer_cnt[18]));
  DFCNQD1 \timer_cnt_reg[19] (.CDN (n_12), .CP (clk), .D (n_109), .Q
       (timer_cnt[19]));
  DFCNQD1 \timer_cnt_reg[20] (.CDN (n_12), .CP (clk), .D (n_108), .Q
       (timer_cnt[20]));
  DFCNQD1 \timer_cnt_reg[21] (.CDN (n_12), .CP (clk), .D (n_121), .Q
       (timer_cnt[21]));
  DFCNQD1 \timer_cnt_reg[22] (.CDN (n_12), .CP (clk), .D (n_107), .Q
       (timer_cnt[22]));
  DFCNQD1 \timer_cnt_reg[23] (.CDN (n_12), .CP (clk), .D (n_106), .Q
       (timer_cnt[23]));
  DFCNQD1 \timer_cnt_reg[24] (.CDN (n_12), .CP (clk), .D (n_105), .Q
       (timer_cnt[24]));
  DFCNQD1 \timer_cnt_reg[25] (.CDN (n_12), .CP (clk), .D (n_104), .Q
       (timer_cnt[25]));
  DFCNQD1 \timer_cnt_reg[26] (.CDN (n_12), .CP (clk), .D (n_103), .Q
       (timer_cnt[26]));
  DFCNQD1 \timer_cnt_reg[27] (.CDN (n_12), .CP (clk), .D (n_123), .Q
       (timer_cnt[27]));
  DFCNQD1 \timer_cnt_reg[28] (.CDN (n_12), .CP (clk), .D (n_102), .Q
       (timer_cnt[28]));
  DFCNQD1 \timer_cnt_reg[29] (.CDN (n_12), .CP (clk), .D (n_120), .Q
       (timer_cnt[29]));
  DFCNQD1 \timer_cnt_reg[30] (.CDN (n_12), .CP (clk), .D (n_101), .Q
       (timer_cnt[30]));
  DFCNQD1 \timer_cnt_reg[31] (.CDN (n_12), .CP (clk), .D (n_135), .Q
       (timer_cnt[31]));
  OAI21D1 g14239__6783(.A1 (n_294), .A2 (n_29), .B (n_31), .ZN (n_354));
  INR2XD0 g14265__3680(.A1 (n_435), .B1 (n_6), .ZN (n_353));
  INR2XD0 g14266__1617(.A1 (n_434), .B1 (n_6), .ZN (n_352));
  INR2XD0 g14267__2802(.A1 (n_433), .B1 (n_6), .ZN (n_351));
  NR2XD0 g14268__1705(.A1 (n_7), .A2 (db_latch_cnt[0]), .ZN (n_350));
  INR2XD0 g14269__5122(.A1 (n_393), .B1 (n_7), .ZN (n_349));
  INR2XD0 g14270__8246(.A1 (n_394), .B1 (n_7), .ZN (n_348));
  INR2XD0 g14271__7098(.A1 (n_395), .B1 (n_7), .ZN (n_347));
  INR2XD0 g14272__6131(.A1 (n_396), .B1 (n_7), .ZN (n_346));
  INR2XD0 g14273__1881(.A1 (n_397), .B1 (n_7), .ZN (n_345));
  INR2XD0 g14274__5115(.A1 (n_399), .B1 (n_7), .ZN (n_344));
  INR2XD0 g14275__7482(.A1 (n_400), .B1 (n_7), .ZN (n_343));
  INR2XD0 g14276__4733(.A1 (n_398), .B1 (n_7), .ZN (n_342));
  INR2XD0 g14277__6161(.A1 (n_401), .B1 (n_7), .ZN (n_341));
  INR2XD0 g14278__9315(.A1 (n_402), .B1 (n_7), .ZN (n_340));
  INR2XD0 g14279__9945(.A1 (n_403), .B1 (n_7), .ZN (n_339));
  INR2XD0 g14280__2883(.A1 (n_404), .B1 (n_7), .ZN (n_338));
  INR2XD0 g14281__2346(.A1 (n_405), .B1 (n_7), .ZN (n_337));
  INR2XD0 g14282__1666(.A1 (n_406), .B1 (n_7), .ZN (n_336));
  INR2XD0 g14283__7410(.A1 (n_407), .B1 (n_7), .ZN (n_335));
  INR2XD0 g14284__6417(.A1 (n_408), .B1 (n_7), .ZN (n_334));
  INR2XD0 g14285__5477(.A1 (n_409), .B1 (n_7), .ZN (n_333));
  NR2XD0 g14287__2398(.A1 (n_6), .A2 (db_read_cnt[0]), .ZN (n_331));
  INR2XD0 g14288__5107(.A1 (n_429), .B1 (n_6), .ZN (n_330));
  INR2XD0 g14289__6260(.A1 (n_430), .B1 (n_6), .ZN (n_329));
  INR2XD0 g14290__4319(.A1 (n_431), .B1 (n_6), .ZN (n_328));
  INR2XD0 g14291__8428(.A1 (n_432), .B1 (n_6), .ZN (n_327));
  INR2XD0 g14296__5526(.A1 (n_437), .B1 (n_6), .ZN (n_325));
  INR2XD0 g14297__6783(.A1 (n_438), .B1 (n_6), .ZN (n_324));
  INR2XD0 g14298__3680(.A1 (n_439), .B1 (n_6), .ZN (n_323));
  INR2XD0 g14299__1617(.A1 (n_440), .B1 (n_6), .ZN (n_322));
  INR2XD0 g14300__2802(.A1 (n_441), .B1 (n_6), .ZN (n_321));
  INR2XD0 g14301__1705(.A1 (n_442), .B1 (n_6), .ZN (n_320));
  INR2XD0 g14302__5122(.A1 (n_443), .B1 (n_6), .ZN (n_319));
  INR2XD0 g14303__8246(.A1 (n_444), .B1 (n_6), .ZN (n_318));
  INR2XD0 g14304__7098(.A1 (n_445), .B1 (n_6), .ZN (n_317));
  INR2XD0 g14306__6131(.A1 (n_411), .B1 (n_5), .ZN (n_315));
  NR2XD0 g14307__1881(.A1 (n_5), .A2 (db_write_cnt[0]), .ZN (n_314));
  INR2XD0 g14308__5115(.A1 (n_412), .B1 (n_5), .ZN (n_313));
  INR2XD0 g14309__7482(.A1 (n_413), .B1 (n_5), .ZN (n_312));
  INR2XD0 g14310__4733(.A1 (n_414), .B1 (n_5), .ZN (n_311));
  INR2XD0 g14311__6161(.A1 (n_415), .B1 (n_5), .ZN (n_310));
  INR2XD0 g14312__9315(.A1 (n_416), .B1 (n_5), .ZN (n_309));
  INR2XD0 g14313__9945(.A1 (n_417), .B1 (n_5), .ZN (n_308));
  INR2XD0 g14314__2883(.A1 (n_418), .B1 (n_5), .ZN (n_307));
  INR2XD0 g14315__2346(.A1 (n_419), .B1 (n_5), .ZN (n_306));
  INR2XD0 g14316__1666(.A1 (n_420), .B1 (n_5), .ZN (n_305));
  INR2XD0 g14317__7410(.A1 (n_421), .B1 (n_5), .ZN (n_304));
  INR2XD0 g14318__6417(.A1 (n_422), .B1 (n_5), .ZN (n_303));
  INR2XD0 g14319__5477(.A1 (n_423), .B1 (n_5), .ZN (n_302));
  INR2XD0 g14320__2398(.A1 (n_424), .B1 (n_5), .ZN (n_301));
  INR2XD0 g14321__5107(.A1 (n_426), .B1 (n_5), .ZN (n_300));
  INR2XD0 g14322__6260(.A1 (n_427), .B1 (n_5), .ZN (n_299));
  INR2XD0 g14323__4319(.A1 (n_425), .B1 (n_5), .ZN (n_298));
  INR2XD0 g14324__8428(.A1 (n_436), .B1 (n_6), .ZN (n_297));
  NR2XD0 g14325__5526(.A1 (n_485), .A2 (n_62), .ZN (n_296));
  NR2XD0 g14326__6783(.A1 (n_484), .A2 (n_3), .ZN (n_295));
  MOAI22D1 g14329__3680(.A1 (n_288), .A2 (n_262), .B1 (n_288), .B2
       (ctrl_state[1]), .ZN (n_293));
  OR4D1 g14330__1617(.A1 (master_data_rd[6]), .A2 (master_data_rd[2]),
       .A3 (master_data_rd[3]), .A4 (n_286), .Z (n_294));
  NR2XD0 g14331__2802(.A1 (n_486), .A2 (n_0), .ZN (n_292));
  NR4D0 g14355__7098(.A1 (n_267), .A2 (n_137), .A3 (n_88), .A4 (n_23),
       .ZN (n_288));
  MOAI22D1 g14356__6131(.A1 (n_268), .A2 (n_206), .B1 (n_268), .B2
       (spi_shifter_out[5]), .ZN (n_287));
  OR4D1 g14357__1881(.A1 (master_data_rd[5]), .A2 (master_data_rd[7]),
       .A3 (master_data_rd[4]), .A4 (n_261), .Z (n_286));
  AO32D1 g14358__5115(.A1 (n_269), .A2 (n_78), .A3 (master_data_wr[0]),
       .B1 (n_268), .B2 (spi_shifter_out[0]), .Z (n_285));
  MOAI22D1 g14359__7482(.A1 (n_268), .A2 (n_209), .B1 (n_268), .B2
       (spi_shifter_out[2]), .ZN (n_284));
  MOAI22D1 g14360__4733(.A1 (n_268), .A2 (n_208), .B1 (n_268), .B2
       (spi_shifter_out[3]), .ZN (n_283));
  MOAI22D1 g14361__6161(.A1 (n_268), .A2 (n_207), .B1 (n_268), .B2
       (spi_shifter_out[4]), .ZN (n_282));
  MOAI22D1 g14363__9315(.A1 (n_268), .A2 (n_211), .B1 (n_268), .B2
       (spi_shifter_out[10]), .ZN (n_281));
  MOAI22D1 g14364__9945(.A1 (n_268), .A2 (n_204), .B1 (n_268), .B2
       (spi_shifter_out[7]), .ZN (n_280));
  MOAI22D1 g14365__2883(.A1 (n_268), .A2 (n_203), .B1 (n_268), .B2
       (spi_shifter_out[8]), .ZN (n_279));
  MOAI22D1 g14366__2346(.A1 (n_268), .A2 (n_202), .B1 (n_268), .B2
       (spi_shifter_out[9]), .ZN (n_278));
  MOAI22D1 g14367__1666(.A1 (n_268), .A2 (n_205), .B1 (n_268), .B2
       (spi_shifter_out[6]), .ZN (n_277));
  MOAI22D1 g14368__7410(.A1 (n_268), .A2 (n_212), .B1 (n_268), .B2
       (spi_shifter_out[11]), .ZN (n_276));
  MOAI22D1 g14369__6417(.A1 (n_268), .A2 (n_215), .B1 (n_268), .B2
       (spi_shifter_out[12]), .ZN (n_275));
  MOAI22D1 g14370__5477(.A1 (n_268), .A2 (n_218), .B1 (n_268), .B2
       (spi_shifter_out[13]), .ZN (n_274));
  OA211D1 g14371__2398(.A1 (db_latch_cnt[13]), .A2 (n_240), .B
       (db_latch_cnt[14]), .C (db_latch_cnt[15]), .Z (n_272));
  ND3D1 g14372__5107(.A1 (n_260), .A2 (n_77), .A3 (n_84), .ZN (n_273));
  OA211D1 g14373__6260(.A1 (db_read_cnt[13]), .A2 (n_239), .B
       (db_read_cnt[14]), .C (db_read_cnt[15]), .Z (n_271));
  OA211D1 g14374__4319(.A1 (db_write_cnt[13]), .A2 (n_238), .B
       (db_write_cnt[14]), .C (db_write_cnt[15]), .Z (n_270));
  CKND1 g14390(.I (n_269), .ZN (n_268));
  IND4D1 g14391__8428(.A1 (n_229), .B1 (n_119), .B2 (n_382), .B3
       (n_380), .ZN (n_267));
  OAI221D0 g14406__5526(.A1 (n_231), .A2 (n_93), .B1
       (master_cmd_packet[1]), .B2 (n_77), .C (n_84), .ZN (n_269));
  AO32D1 g14436__6783(.A1 (n_234), .A2 (n_80), .A3 (spi_shifter_in[6]),
       .B1 (n_235), .B2 (spi_shifter_in[7]), .Z (n_266));
  AO22D0 g14437__3680(.A1 (n_227), .A2 (spi_bitcnt[3]), .B1 (n_142),
       .B2 (n_200), .Z (n_265));
  AO22D0 g14438__1617(.A1 (n_226), .A2 (spi_bitcnt[2]), .B1 (n_87), .B2
       (n_200), .Z (n_264));
  AO22D0 g14439__2802(.A1 (n_228), .A2 (spi_bitcnt[1]), .B1 (n_25), .B2
       (n_200), .Z (n_263));
  INR4D0 g14440__1705(.A1 (n_384), .B1 (n_86), .B2 (n_88), .B3 (n_223),
       .ZN (n_262));
  OR4D1 g14441__5122(.A1 (master_data_rd[8]), .A2 (master_data_rd[11]),
       .A3 (master_data_rd[10]), .A4 (n_210), .Z (n_261));
  AOI211D1 g14442__8246(.A1 (n_213), .A2 (n_85), .B (n_222), .C
       (spi_state[2]), .ZN (n_260));
  AO32D1 g14443__7098(.A1 (n_234), .A2 (n_80), .A3 (spi_miso_in), .B1
       (n_235), .B2 (spi_shifter_in[0]), .Z (n_259));
  AO32D1 g14444__6131(.A1 (n_234), .A2 (n_80), .A3 (spi_shifter_in[0]),
       .B1 (n_235), .B2 (spi_shifter_in[1]), .Z (n_258));
  AO32D1 g14445__1881(.A1 (n_234), .A2 (n_80), .A3 (spi_shifter_in[1]),
       .B1 (n_235), .B2 (spi_shifter_in[2]), .Z (n_257));
  AO32D1 g14446__5115(.A1 (n_234), .A2 (n_80), .A3 (spi_shifter_in[2]),
       .B1 (n_235), .B2 (spi_shifter_in[3]), .Z (n_256));
  AO32D1 g14447__7482(.A1 (n_234), .A2 (n_80), .A3 (spi_shifter_in[3]),
       .B1 (n_235), .B2 (spi_shifter_in[4]), .Z (n_255));
  AO32D1 g14448__4733(.A1 (n_234), .A2 (n_80), .A3 (spi_shifter_in[4]),
       .B1 (n_235), .B2 (spi_shifter_in[5]), .Z (n_254));
  AO32D1 g14449__6161(.A1 (n_234), .A2 (n_80), .A3 (spi_shifter_in[5]),
       .B1 (n_235), .B2 (spi_shifter_in[6]), .Z (n_253));
  MOAI22D1 g14450__9315(.A1 (n_236), .A2 (n_84), .B1 (n_236), .B2
       (spi_active), .ZN (n_252));
  AO32D1 g14451__9945(.A1 (n_234), .A2 (n_80), .A3 (spi_shifter_in[7]),
       .B1 (n_235), .B2 (spi_shifter_in[8]), .Z (n_251));
  AO32D1 g14452__2883(.A1 (n_234), .A2 (n_80), .A3 (spi_shifter_in[8]),
       .B1 (n_235), .B2 (spi_shifter_in[9]), .Z (n_250));
  AO32D1 g14453__2346(.A1 (n_234), .A2 (n_80), .A3 (spi_shifter_in[9]),
       .B1 (n_235), .B2 (spi_shifter_in[10]), .Z (n_249));
  AO32D1 g14454__1666(.A1 (n_234), .A2 (n_80), .A3
       (spi_shifter_in[10]), .B1 (n_235), .B2 (spi_shifter_in[11]), .Z
       (n_248));
  AO32D1 g14455__7410(.A1 (n_234), .A2 (n_80), .A3
       (spi_shifter_in[11]), .B1 (n_235), .B2 (spi_shifter_in[12]), .Z
       (n_247));
  AO32D1 g14456__6417(.A1 (n_234), .A2 (n_80), .A3
       (spi_shifter_in[12]), .B1 (n_235), .B2 (spi_shifter_in[13]), .Z
       (n_246));
  AO32D1 g14457__5477(.A1 (n_234), .A2 (n_80), .A3
       (spi_shifter_in[13]), .B1 (n_235), .B2 (spi_shifter_in[14]), .Z
       (n_245));
  AO32D1 g14458__2398(.A1 (n_234), .A2 (n_80), .A3
       (spi_shifter_in[14]), .B1 (n_235), .B2 (spi_shifter_in[15]), .Z
       (n_244));
  AO22D0 g14459__5107(.A1 (n_225), .A2 (n_184), .B1 (spi_bitcnt[4]),
       .B2 (n_232), .Z (n_243));
  OAI22D1 g14460__6260(.A1 (n_230), .A2 (master_cmd_packet[1]), .B1
       (n_231), .B2 (n_17), .ZN (n_242));
  IND4D1 g14466__4319(.A1 (n_378), .B1 (n_199), .B2 (n_377), .B3
       (n_381), .ZN (n_241));
  OA31D1 g14467__8428(.A1 (db_latch_cnt[11]), .A2 (db_latch_cnt[10]),
       .A3 (n_189), .B (db_latch_cnt[12]), .Z (n_240));
  OA31D1 g14468__5526(.A1 (db_read_cnt[11]), .A2 (db_read_cnt[10]), .A3
       (n_188), .B (db_read_cnt[12]), .Z (n_239));
  OA31D1 g14469__6783(.A1 (db_write_cnt[11]), .A2 (db_write_cnt[10]),
       .A3 (n_187), .B (db_write_cnt[12]), .Z (n_238));
  OAI32D1 g14470__3680(.A1 (ctrl_btn_write_s_db), .A2 (n_35), .A3
       (n_219), .B1 (n_10), .B2 (n_220), .ZN (n_237));
  CKND1 g14471(.I (n_235), .ZN (n_234));
  ND2D1 g14472__1617(.A1 (n_217), .A2 (n_32), .ZN (n_233));
  ND2D1 g14473__2802(.A1 (n_225), .A2 (n_142), .ZN (n_232));
  NR2XD0 g14476__1705(.A1 (n_222), .A2 (n_34), .ZN (n_236));
  OAI21D1 g14477__5122(.A1 (n_190), .A2 (n_78), .B
       (master_cmd_packet[1]), .ZN (n_235));
  AOI31D1 g14478__8246(.A1 (n_174), .A2 (n_80), .A3
       (spi_shifter_out[15]), .B (n_147), .ZN (n_230));
  OAI211D1 g14479__7098(.A1 (n_391), .A2 (n_28), .B (n_182), .C
       (n_376), .ZN (n_229));
  IOA21D1 g14480__6131(.A1 (spi_state[0]), .A2 (spi_bitcnt[0]), .B
       (n_225), .ZN (n_228));
  OAI21D1 g14481__1881(.A1 (n_87), .A2 (n_15), .B (n_225), .ZN (n_227));
  OAI21D1 g14482__5115(.A1 (n_25), .A2 (n_15), .B (n_225), .ZN (n_226));
  AOI31D1 g14483__7482(.A1 (n_173), .A2 (n_80), .A3 (n_10), .B (n_85),
       .ZN (n_231));
  INVD1 g14484(.I (n_224), .ZN (n_225));
  IND4D1 g14485__4733(.A1 (n_378), .B1 (n_126), .B2 (n_379), .B3
       (n_383), .ZN (n_223));
  NR2D1 g14504__6161(.A1 (n_200), .A2 (n_83), .ZN (n_224));
  CKND1 g14505(.I (n_220), .ZN (n_219));
  AOI222D0 g14506__9315(.A1 (n_138), .A2 (spi_shifter_out[12]), .B1
       (n_34), .B2 (master_cmd_packet[13]), .C1 (n_78), .C2
       (master_data_wr[13]), .ZN (n_218));
  INR4D0 g14507__9945(.A1 (n_383), .B1 (n_23), .B2 (n_86), .B3 (n_146),
       .ZN (n_217));
  IND4D1 g14508__2883(.A1 (n_86), .B1 (n_119), .B2 (n_96), .B3 (n_382),
       .ZN (n_216));
  AOI222D0 g14509__2346(.A1 (n_138), .A2 (spi_shifter_out[11]), .B1
       (n_34), .B2 (master_cmd_packet[12]), .C1 (n_78), .C2
       (master_data_wr[12]), .ZN (n_215));
  IOA21D1 g14510__1666(.A1 (n_78), .A2 (master_data_wr[1]), .B (n_180),
       .ZN (n_214));
  INR3D0 g14511__7410(.A1 (spi_bitcnt[0]), .B1 (spi_bitcnt[1]), .B2
       (n_177), .ZN (n_213));
  AOI222D0 g14512__6417(.A1 (n_138), .A2 (spi_shifter_out[10]), .B1
       (n_34), .B2 (master_cmd_packet[11]), .C1 (n_78), .C2
       (master_data_wr[11]), .ZN (n_212));
  AOI222D0 g14513__5477(.A1 (n_138), .A2 (spi_shifter_out[9]), .B1
       (n_34), .B2 (master_cmd_packet[10]), .C1 (n_78), .C2
       (master_data_wr[10]), .ZN (n_211));
  OR4D1 g14514__2398(.A1 (master_data_rd[14]), .A2 (master_data_rd[9]),
       .A3 (master_data_rd[15]), .A4 (n_97), .Z (n_210));
  AOI222D0 g14515__5107(.A1 (n_138), .A2 (spi_shifter_out[1]), .B1
       (n_34), .B2 (master_cmd_packet[2]), .C1 (n_78), .C2
       (master_data_wr[2]), .ZN (n_209));
  AOI222D0 g14516__6260(.A1 (n_138), .A2 (spi_shifter_out[2]), .B1
       (n_34), .B2 (master_cmd_packet[3]), .C1 (n_78), .C2
       (master_data_wr[3]), .ZN (n_208));
  AOI222D0 g14517__4319(.A1 (n_138), .A2 (spi_shifter_out[3]), .B1
       (n_34), .B2 (master_cmd_packet[4]), .C1 (n_78), .C2
       (master_data_wr[4]), .ZN (n_207));
  AOI222D0 g14518__8428(.A1 (n_138), .A2 (spi_shifter_out[4]), .B1
       (n_34), .B2 (master_cmd_packet[5]), .C1 (n_78), .C2
       (master_data_wr[5]), .ZN (n_206));
  AOI222D0 g14519__5526(.A1 (n_138), .A2 (spi_shifter_out[5]), .B1
       (n_34), .B2 (master_cmd_packet[6]), .C1 (n_78), .C2
       (master_data_wr[6]), .ZN (n_205));
  AOI222D0 g14520__6783(.A1 (n_138), .A2 (spi_shifter_out[6]), .B1
       (n_34), .B2 (master_cmd_packet[7]), .C1 (n_78), .C2
       (master_data_wr[7]), .ZN (n_204));
  AOI222D0 g14521__3680(.A1 (n_138), .A2 (spi_shifter_out[7]), .B1
       (n_34), .B2 (master_cmd_packet[8]), .C1 (n_78), .C2
       (master_data_wr[8]), .ZN (n_203));
  AOI222D0 g14522__1617(.A1 (n_138), .A2 (spi_shifter_out[8]), .B1
       (n_34), .B2 (master_cmd_packet[9]), .C1 (n_78), .C2
       (master_data_wr[9]), .ZN (n_202));
  OAI211D1 g14523__2802(.A1 (n_93), .A2 (n_139), .B (n_77), .C (n_84),
       .ZN (n_201));
  INR3D0 g14524__1705(.A1 (n_25), .B1 (n_79), .B2 (n_177), .ZN (n_222));
  AOI21D1 g14525__5122(.A1 (n_172), .A2 (n_23), .B (n_146), .ZN
       (n_221));
  ND2D1 g14526__8246(.A1 (n_178), .A2 (n_32), .ZN (n_220));
  IND2D1 g14527__7098(.A1 (n_172), .B1 (n_23), .ZN (n_199));
  CKND2D1 g14528__6131(.A1 (n_170), .A2 (master_cmd_packet[12]), .ZN
       (n_198));
  OR2D1 g14529__1881(.A1 (n_175), .A2 (master_cmd_packet[12]), .Z
       (n_197));
  IND2D1 g14530__5115(.A1 (n_175), .B1 (master_cmd_packet[12]), .ZN
       (n_196));
  CKND2D1 g14531__7482(.A1 (n_176), .A2 (n_13), .ZN (n_195));
  CKND2D1 g14532__4733(.A1 (n_2), .A2 (n_13), .ZN (n_194));
  CKND2D1 g14533__6161(.A1 (n_176), .A2 (master_cmd_packet[12]), .ZN
       (n_193));
  CKND2D1 g14534__9315(.A1 (n_2), .A2 (master_cmd_packet[12]), .ZN
       (n_192));
  CKND2D1 g14535__9945(.A1 (n_170), .A2 (n_13), .ZN (n_191));
  NR2XD0 g14539__2883(.A1 (n_171), .A2 (n_139), .ZN (n_200));
  NR2D1 g14540__2346(.A1 (n_171), .A2 (n_79), .ZN (n_190));
  AO211D1 g14541__1666(.A1 (n_65), .A2 (db_latch_cnt[7]), .B
       (db_latch_cnt[9]), .C (db_latch_cnt[8]), .Z (n_189));
  AO211D1 g14542__7410(.A1 (n_64), .A2 (db_read_cnt[7]), .B
       (db_read_cnt[9]), .C (db_read_cnt[8]), .Z (n_188));
  AO211D1 g14543__6417(.A1 (n_76), .A2 (db_write_cnt[7]), .B
       (db_write_cnt[9]), .C (db_write_cnt[8]), .Z (n_187));
  OA21D1 g14544__5477(.A1 (n_37), .A2 (ctrl_gw_idx[2]), .B (n_23), .Z
       (n_186));
  AO21D1 g14545__2398(.A1 (n_138), .A2 (spi_shifter_out[14]), .B
       (n_147), .Z (n_185));
  OAI31D1 g14546__5107(.A1 (spi_state[1]), .A2 (spi_bitcnt[1]), .A3
       (n_91), .B (n_392), .ZN (n_184));
  AO211D1 g14547__6260(.A1 (spi_divcnt[1]), .A2 (spi_divcnt[0]), .B
       (n_140), .C (n_26), .Z (n_183));
  AOI22D1 g14548__4319(.A1 (n_122), .A2 (master_tx_done), .B1 (n_36),
       .B2 (ctrl_btn_read_s_db), .ZN (n_182));
  AO22D0 g14549__8428(.A1 (n_143), .A2 (spi_active), .B1
       (spi_sclk_out), .B2 (n_141), .Z (n_181));
  OAI22D1 g14550__5526(.A1 (n_138), .A2 (master_cmd_packet[1]), .B1
       (n_34), .B2 (spi_shifter_out[0]), .ZN (n_180));
  AO22D0 g14551__6783(.A1 (n_138), .A2 (spi_shifter_out[13]), .B1
       (master_data_wr[14]), .B2 (n_78), .Z (n_179));
  OA22D0 g14552__3680(.A1 (n_144), .A2 (ctrl_btn_write_s_db), .B1
       (ctrl_latched_global), .B2 (n_136), .Z (n_178));
  CKND1 g14605(.I (n_173), .ZN (n_174));
  AO22D0 g14606__1617(.A1 (n_82), .A2 (sw[15]), .B1
       (ctrl_latched_write_data[15]), .B2 (n_33), .Z (n_169));
  AO22D0 g14607__2802(.A1 (n_82), .A2 (sw[7]), .B1
       (ctrl_latched_write_data[7]), .B2 (n_33), .Z (n_168));
  AO22D0 g14608__1705(.A1 (n_82), .A2 (sw[6]), .B1
       (ctrl_latched_write_data[6]), .B2 (n_33), .Z (n_167));
  AO22D0 g14609__5122(.A1 (n_82), .A2 (sw[5]), .B1
       (ctrl_latched_write_data[5]), .B2 (n_33), .Z (n_166));
  AO22D0 g14610__8246(.A1 (n_82), .A2 (sw[4]), .B1
       (ctrl_latched_write_data[4]), .B2 (n_33), .Z (n_165));
  AO22D0 g14611__7098(.A1 (n_82), .A2 (sw[3]), .B1
       (ctrl_latched_write_data[3]), .B2 (n_33), .Z (n_164));
  AO22D0 g14612__6131(.A1 (n_82), .A2 (sw[2]), .B1
       (ctrl_latched_write_data[2]), .B2 (n_33), .Z (n_163));
  AO22D0 g14613__1881(.A1 (n_82), .A2 (sw[1]), .B1
       (ctrl_latched_write_data[1]), .B2 (n_33), .Z (n_162));
  AO22D0 g14614__5115(.A1 (n_82), .A2 (sw[0]), .B1
       (ctrl_latched_write_data[0]), .B2 (n_33), .Z (n_161));
  AO22D0 g14615__7482(.A1 (n_82), .A2 (sw[8]), .B1
       (ctrl_latched_write_data[8]), .B2 (n_33), .Z (n_160));
  AO22D0 g14616__4733(.A1 (n_82), .A2 (sw[14]), .B1
       (ctrl_latched_write_data[14]), .B2 (n_33), .Z (n_159));
  AO22D0 g14617__6161(.A1 (n_82), .A2 (sw[13]), .B1
       (ctrl_latched_write_data[13]), .B2 (n_33), .Z (n_158));
  AO22D0 g14618__9315(.A1 (n_82), .A2 (sw[12]), .B1
       (ctrl_latched_write_data[12]), .B2 (n_33), .Z (n_157));
  ND2D1 g14619__9945(.A1 (n_141), .A2 (spi_divcnt[0]), .ZN (n_156));
  NR2XD0 g14620__2883(.A1 (n_38), .A2 (n_22), .ZN (n_155));
  OAI21D1 g14621__2346(.A1 (n_26), .A2 (n_11), .B (n_141), .ZN (n_154));
  AO22D0 g14622__1666(.A1 (n_82), .A2 (sw[9]), .B1
       (ctrl_latched_write_data[9]), .B2 (n_33), .Z (n_153));
  AO22D0 g14623__7410(.A1 (n_82), .A2 (sw[10]), .B1
       (ctrl_latched_write_data[10]), .B2 (n_33), .Z (n_152));
  AO22D0 g14624__6417(.A1 (n_82), .A2 (sw[11]), .B1
       (ctrl_latched_write_data[11]), .B2 (n_33), .Z (n_151));
  IND2D1 g14630__5477(.A1 (n_91), .B1 (n_143), .ZN (n_177));
  INR2XD0 g14631__2398(.A1 (n_145), .B1 (master_cmd_packet[13]), .ZN
       (n_176));
  CKND2D1 g14633__5107(.A1 (n_145), .A2 (master_cmd_packet[13]), .ZN
       (n_175));
  CKND2D1 g14635__6260(.A1 (n_142), .A2 (spi_bitcnt[4]), .ZN (n_173));
  CKND2D1 g14636__4319(.A1 (n_37), .A2 (ctrl_gw_idx[2]), .ZN (n_172));
  ND2D1 g14637__8428(.A1 (n_136), .A2 (n_375), .ZN (n_150));
  ND2D1 g14638__5526(.A1 (n_136), .A2 (n_144), .ZN (n_149));
  OAI21D1 g14641__6783(.A1 (n_91), .A2 (n_24), .B (n_143), .ZN (n_171));
  NR2XD0 g14645__3680(.A1 (n_148), .A2 (master_cmd_packet[13]), .ZN
       (n_170));
  INVD1 g14659(.I (n_140), .ZN (n_141));
  CKND1 g14660(.I (n_139), .ZN (n_138));
  CKND1 g14661(.I (n_137), .ZN (n_136));
  NR2XD0 g14662__1617(.A1 (n_45), .A2 (n_20), .ZN (n_135));
  NR2XD0 g14663__2802(.A1 (n_52), .A2 (n_20), .ZN (n_134));
  NR2XD0 g14664__1705(.A1 (n_42), .A2 (n_20), .ZN (n_133));
  NR2XD0 g14665__5122(.A1 (n_40), .A2 (n_20), .ZN (n_132));
  NR2XD0 g14666__8246(.A1 (n_71), .A2 (n_20), .ZN (n_131));
  NR2XD0 g14667__7098(.A1 (n_67), .A2 (n_20), .ZN (n_130));
  NR2XD0 g14668__6131(.A1 (n_58), .A2 (n_20), .ZN (n_129));
  NR2XD0 g14669__1881(.A1 (n_66), .A2 (n_20), .ZN (n_128));
  NR2XD0 g14670__5115(.A1 (n_41), .A2 (n_20), .ZN (n_127));
  ND2D1 g14671__7482(.A1 (n_90), .A2 (n_27), .ZN (n_126));
  NR2XD0 g14672__4733(.A1 (n_73), .A2 (n_20), .ZN (n_125));
  IND2D1 g14673__6161(.A1 (n_85), .B1 (n_77), .ZN (n_124));
  NR2XD0 g14674__9315(.A1 (n_47), .A2 (n_20), .ZN (n_123));
  IND2D1 g14675__9945(.A1 (n_86), .B1 (n_381), .ZN (n_122));
  NR2XD0 g14676__2883(.A1 (n_54), .A2 (n_20), .ZN (n_121));
  NR2XD0 g14677__2346(.A1 (n_75), .A2 (n_20), .ZN (n_120));
  CKND2D1 g14678__1666(.A1 (n_83), .A2 (master_cmd_packet[11]), .ZN
       (n_148));
  INR2D1 g14679__7410(.A1 (master_data_wr[15]), .B1 (n_77), .ZN
       (n_147));
  NR2D1 g14680__6417(.A1 (n_89), .A2 (n_27), .ZN (n_146));
  NR2XD0 g14681__5477(.A1 (n_84), .A2 (master_cmd_packet[11]), .ZN
       (n_145));
  CKND2D1 g14682__2398(.A1 (n_90), .A2 (ctrl_btn_read_s_db), .ZN
       (n_144));
  NR2XD0 g14683__5107(.A1 (n_92), .A2 (spi_sclk_out), .ZN (n_143));
  INR2XD0 g14684__6260(.A1 (n_87), .B1 (spi_bitcnt[3]), .ZN (n_142));
  ND2D1 g14685__4319(.A1 (n_92), .A2 (spi_active), .ZN (n_140));
  NR2XD0 g14686__8428(.A1 (n_85), .A2 (n_80), .ZN (n_139));
  NR2XD0 g14687__5526(.A1 (n_81), .A2 (ctrl_btn_latch_db), .ZN (n_137));
  NR2XD0 g14689__6783(.A1 (n_56), .A2 (n_20), .ZN (n_118));
  NR2XD0 g14690__3680(.A1 (n_51), .A2 (n_20), .ZN (n_117));
  NR2XD0 g14691__1617(.A1 (n_57), .A2 (n_20), .ZN (n_116));
  NR2XD0 g14692__2802(.A1 (n_61), .A2 (n_20), .ZN (n_115));
  NR2XD0 g14693__1705(.A1 (n_48), .A2 (n_20), .ZN (n_114));
  NR2XD0 g14694__5122(.A1 (n_55), .A2 (n_20), .ZN (n_113));
  NR2XD0 g14695__8246(.A1 (n_70), .A2 (n_20), .ZN (n_112));
  NR2XD0 g14696__7098(.A1 (n_43), .A2 (n_20), .ZN (n_111));
  NR2XD0 g14697__6131(.A1 (n_69), .A2 (n_20), .ZN (n_110));
  NR2XD0 g14698__1881(.A1 (n_50), .A2 (n_20), .ZN (n_109));
  NR2XD0 g14699__5115(.A1 (n_53), .A2 (n_20), .ZN (n_108));
  NR2XD0 g14700__7482(.A1 (n_74), .A2 (n_20), .ZN (n_107));
  NR2XD0 g14701__4733(.A1 (n_49), .A2 (n_20), .ZN (n_106));
  NR2XD0 g14702__6161(.A1 (n_68), .A2 (n_20), .ZN (n_105));
  NR2XD0 g14703__9315(.A1 (n_60), .A2 (n_20), .ZN (n_104));
  NR2XD0 g14704__9945(.A1 (n_59), .A2 (n_20), .ZN (n_103));
  NR2XD0 g14705__2883(.A1 (n_46), .A2 (n_20), .ZN (n_102));
  NR2XD0 g14706__2346(.A1 (n_44), .A2 (n_20), .ZN (n_101));
  AO22D0 g14708__1666(.A1 (n_36), .A2 (ctrl_latched_id[2]), .B1
       (ctrl_gw_idx[2]), .B2 (n_33), .Z (n_100));
  NR2XD0 g14709__7410(.A1 (n_39), .A2 (n_20), .ZN (n_99));
  AO22D0 g14710__6417(.A1 (n_36), .A2 (ctrl_latched_id[1]), .B1
       (ctrl_gw_idx[1]), .B2 (n_33), .Z (n_98));
  OR4D1 g14711__5477(.A1 (master_data_rd[0]), .A2 (master_data_rd[1]),
       .A3 (master_data_rd[12]), .A4 (master_data_rd[13]), .Z (n_97));
  MAOI22D1 g14712__2398(.A1 (n_36), .A2 (n_27), .B1 (n_381), .B2
       (ctrl_last_op_was_write), .ZN (n_96));
  AO22D0 g14713__5107(.A1 (n_36), .A2 (ctrl_latched_id[0]), .B1
       (ctrl_gw_idx[0]), .B2 (n_33), .Z (n_95));
  AOI21D1 g14714__6260(.A1 (n_36), .A2 (ctrl_btn_latch_db), .B (n_33),
       .ZN (n_119));
  NR2XD0 g14715__4319(.A1 (n_88), .A2 (n_36), .ZN (n_94));
  CKND1 g14716(.I (n_90), .ZN (n_89));
  INVD1 g14717(.I (n_84), .ZN (n_83));
  CKND1 g14718(.I (n_81), .ZN (n_82));
  INVD1 g14719(.I (n_80), .ZN (n_79));
  INVD1 g14720(.I (n_78), .ZN (n_77));
  OR3D1 g14721__8428(.A1 (db_write_cnt[6]), .A2 (db_write_cnt[5]), .A3
       (db_write_cnt[4]), .Z (n_76));
  AOI22D1 g14722__5526(.A1 (n_9), .A2 (timer_cnt[29]), .B1 (n_451), .B2
       (timer_running), .ZN (n_75));
  AOI22D1 g14723__6783(.A1 (n_9), .A2 (timer_cnt[22]), .B1 (n_458), .B2
       (timer_running), .ZN (n_74));
  AOI22D1 g14724__3680(.A1 (n_9), .A2 (timer_cnt[1]), .B1 (n_479), .B2
       (timer_running), .ZN (n_73));
  NR2XD0 g14725__1617(.A1 (n_22), .A2 (ctrl_gw_idx[0]), .ZN (n_72));
  AOI22D1 g14726__2802(.A1 (n_9), .A2 (timer_cnt[6]), .B1 (n_474), .B2
       (timer_running), .ZN (n_71));
  AOI22D1 g14727__1705(.A1 (n_9), .A2 (timer_cnt[16]), .B1 (n_464), .B2
       (timer_running), .ZN (n_70));
  AOI22D1 g14728__5122(.A1 (n_9), .A2 (timer_cnt[18]), .B1 (n_462), .B2
       (timer_running), .ZN (n_69));
  AOI22D1 g14729__8246(.A1 (n_9), .A2 (timer_cnt[24]), .B1 (n_456), .B2
       (timer_running), .ZN (n_68));
  AOI22D1 g14730__7098(.A1 (n_9), .A2 (timer_cnt[5]), .B1 (n_475), .B2
       (timer_running), .ZN (n_67));
  AOI22D1 g14731__6131(.A1 (n_9), .A2 (timer_cnt[3]), .B1 (n_477), .B2
       (timer_running), .ZN (n_66));
  OR3D1 g14732__1881(.A1 (db_latch_cnt[6]), .A2 (db_latch_cnt[5]), .A3
       (db_latch_cnt[4]), .Z (n_65));
  OR3D1 g14733__5115(.A1 (db_read_cnt[6]), .A2 (db_read_cnt[5]), .A3
       (db_read_cnt[4]), .Z (n_64));
  OAI21D1 g14734__7482(.A1 (n_448), .A2 (n_9), .B (n_19), .ZN (n_63));
  ND3D1 g14735__4733(.A1 (n_26), .A2 (spi_sclk_out), .A3 (n_11), .ZN
       (n_93));
  ND2D1 g14736__6161(.A1 (n_26), .A2 (n_11), .ZN (n_92));
  OR3D1 g14737__9315(.A1 (spi_bitcnt[4]), .A2 (spi_bitcnt[2]), .A3
       (spi_bitcnt[3]), .Z (n_91));
  NR2XD0 g14738__9945(.A1 (n_35), .A2 (ctrl_btn_latch_db), .ZN (n_90));
  CKND2D1 g14739__2883(.A1 (n_29), .A2 (n_31), .ZN (n_88));
  NR2XD0 g14740__2346(.A1 (n_24), .A2 (spi_bitcnt[2]), .ZN (n_87));
  INR3D0 g14741__1666(.A1 (ctrl_state[1]), .B1 (ctrl_state[0]), .B2
       (n_390), .ZN (n_86));
  NR3D0 g14742__7410(.A1 (n_15), .A2 (spi_state[2]), .A3
       (spi_state[1]), .ZN (n_85));
  ND2D1 g14743__6417(.A1 (n_34), .A2 (master_start_tx), .ZN (n_84));
  CKND2D1 g14744__5477(.A1 (n_36), .A2 (ctrl_btn_write_s_db), .ZN
       (n_81));
  NR2XD0 g14745__2398(.A1 (n_1), .A2 (n_15), .ZN (n_80));
  NR2XD0 g14746__5107(.A1 (n_1), .A2 (spi_state[0]), .ZN (n_78));
  AOI22D1 g14750__6260(.A1 (n_9), .A2 (timer_cnt[13]), .B1 (n_467), .B2
       (timer_running), .ZN (n_61));
  AOI22D1 g14751__4319(.A1 (n_9), .A2 (timer_cnt[25]), .B1 (n_455), .B2
       (timer_running), .ZN (n_60));
  AOI22D1 g14752__8428(.A1 (n_9), .A2 (timer_cnt[26]), .B1 (n_454), .B2
       (timer_running), .ZN (n_59));
  AOI22D1 g14753__5526(.A1 (n_9), .A2 (timer_cnt[4]), .B1 (n_476), .B2
       (timer_running), .ZN (n_58));
  AOI22D1 g14754__6783(.A1 (n_9), .A2 (timer_cnt[12]), .B1 (n_468), .B2
       (timer_running), .ZN (n_57));
  AOI22D1 g14755__3680(.A1 (n_9), .A2 (timer_cnt[10]), .B1 (n_470), .B2
       (timer_running), .ZN (n_56));
  AOI22D1 g14756__1617(.A1 (n_9), .A2 (timer_cnt[15]), .B1 (n_465), .B2
       (timer_running), .ZN (n_55));
  AOI22D1 g14757__2802(.A1 (n_9), .A2 (timer_cnt[21]), .B1 (n_459), .B2
       (timer_running), .ZN (n_54));
  AOI22D1 g14758__1705(.A1 (n_9), .A2 (timer_cnt[20]), .B1 (n_460), .B2
       (timer_running), .ZN (n_53));
  AOI22D1 g14759__5122(.A1 (n_9), .A2 (timer_cnt[9]), .B1 (n_471), .B2
       (timer_running), .ZN (n_52));
  AOI22D1 g14760__8246(.A1 (n_9), .A2 (timer_cnt[11]), .B1 (n_469), .B2
       (timer_running), .ZN (n_51));
  AOI22D1 g14761__7098(.A1 (n_9), .A2 (timer_cnt[19]), .B1 (n_461), .B2
       (timer_running), .ZN (n_50));
  AOI22D1 g14762__6131(.A1 (n_9), .A2 (timer_cnt[23]), .B1 (n_457), .B2
       (timer_running), .ZN (n_49));
  AOI22D1 g14763__1881(.A1 (n_9), .A2 (timer_cnt[14]), .B1 (n_466), .B2
       (timer_running), .ZN (n_48));
  AOI22D1 g14764__5115(.A1 (n_9), .A2 (timer_cnt[27]), .B1 (n_453), .B2
       (timer_running), .ZN (n_47));
  AOI22D1 g14765__7482(.A1 (n_9), .A2 (timer_cnt[28]), .B1 (n_452), .B2
       (timer_running), .ZN (n_46));
  AOI22D1 g14766__4733(.A1 (n_9), .A2 (timer_cnt[31]), .B1 (n_449), .B2
       (timer_running), .ZN (n_45));
  AOI22D1 g14767__6161(.A1 (n_9), .A2 (timer_cnt[30]), .B1 (n_450), .B2
       (timer_running), .ZN (n_44));
  AOI22D1 g14768__9315(.A1 (n_9), .A2 (timer_cnt[17]), .B1 (n_463), .B2
       (timer_running), .ZN (n_43));
  AOI22D1 g14769__9945(.A1 (n_9), .A2 (timer_cnt[8]), .B1 (n_472), .B2
       (timer_running), .ZN (n_42));
  AOI22D1 g14770__2883(.A1 (n_9), .A2 (timer_cnt[2]), .B1 (n_478), .B2
       (timer_running), .ZN (n_41));
  AOI22D1 g14771__2346(.A1 (n_9), .A2 (timer_cnt[7]), .B1 (n_473), .B2
       (timer_running), .ZN (n_40));
  MUX2ND0 g14772__1666(.I0 (timer_running), .I1 (n_9), .S
       (timer_cnt[0]), .ZN (n_39));
  MUX2ND0 g14773__7410(.I0 (ctrl_gw_idx[0]), .I1 (n_16), .S
       (ctrl_gw_idx[1]), .ZN (n_38));
  XNR2D1 g14775__6417(.A1 (ctrl_btn_read_s_db), .A2 (db_read_sync1),
       .ZN (n_62));
  INVD1 g14777(.I (n_36), .ZN (n_35));
  INVD1 g14779(.I (n_33), .ZN (n_32));
  INVD1 g14780(.I (n_30), .ZN (n_29));
  ND2D1 g14781__5477(.A1 (ctrl_state[2]), .A2 (ctrl_timer_done), .ZN
       (n_28));
  NR2XD0 g14782__2398(.A1 (n_14), .A2 (n_16), .ZN (n_37));
  NR2XD0 g14783__5107(.A1 (n_389), .A2 (ctrl_state[0]), .ZN (n_36));
  NR2D1 g14784__6260(.A1 (spi_state[2]), .A2 (n_392), .ZN (n_34));
  NR2XD0 g14785__4319(.A1 (n_390), .A2 (n_388), .ZN (n_33));
  OR2XD1 g14786__8428(.A1 (n_389), .A2 (n_387), .Z (n_31));
  NR2D1 g14787__5526(.A1 (n_386), .A2 (n_387), .ZN (n_30));
  INVD1 g14788(.I (n_25), .ZN (n_24));
  CKND1 g14789(.I (n_23), .ZN (n_22));
  INVD1 g14790(.I (n_20), .ZN (n_19));
  IND2D1 g14791__6783(.A1 (n_384), .B1 (ctrl_timer_done), .ZN (n_18));
  ND2D1 g14793__3680(.A1 (ctrl_latched_global), .A2
       (ctrl_btn_write_s_db), .ZN (n_27));
  NR2XD0 g14794__1617(.A1 (spi_divcnt[0]), .A2 (spi_divcnt[1]), .ZN
       (n_26));
  NR2XD0 g14795__2802(.A1 (spi_bitcnt[1]), .A2 (spi_bitcnt[0]), .ZN
       (n_25));
  NR2D1 g14796__1705(.A1 (n_390), .A2 (n_391), .ZN (n_23));
  NR2XD0 g14797__5122(.A1 (n_10), .A2 (n_385), .ZN (n_21));
  AN2XD1 g14798__8246(.A1 (n_9), .A2 (ctrl_timer_start), .Z (n_20));
  CKND1 g14799(.I (spi_shifter_out[14]), .ZN (n_17));
  INVD1 g14801(.I (ctrl_gw_idx[0]), .ZN (n_16));
  INVD1 g14802(.I (spi_state[0]), .ZN (n_15));
  INVD1 g14805(.I (ctrl_gw_idx[1]), .ZN (n_14));
  INVD1 g14812(.I (master_cmd_packet[12]), .ZN (n_13));
  DFCND1 \master_cmd_packet_reg[1] (.CDN (n_12), .CP (clk), .D (n_237),
       .Q (master_cmd_packet[1]), .QN (n_10));
  DFSND1 \spi_divcnt_reg[2] (.SDN (n_12), .CP (clk), .D (n_154), .Q
       (spi_divcnt[2]), .QN (n_11));
  DFCND1 timer_running_reg(.CDN (n_12), .CP (clk), .D (n_63), .Q
       (timer_running), .QN (n_9));
  IND2D1 g2__7098(.A1 (n_3), .B1 (n_484), .ZN (n_7));
  IND2D1 g14837__6131(.A1 (n_62), .B1 (n_485), .ZN (n_6));
  IND2D1 g14838__1881(.A1 (n_0), .B1 (n_486), .ZN (n_5));
  IND2D1 g14839__5115(.A1 (n_34), .B1 (n_77), .ZN (n_4));
  XNR2D1 g14840__7482(.A1 (ctrl_btn_latch_db), .A2 (db_latch_sync1),
       .ZN (n_3));
  INR2D1 g14841__4733(.A1 (master_cmd_packet[13]), .B1 (n_148), .ZN
       (n_2));
  IND2D1 g14842__6161(.A1 (spi_state[2]), .B1 (spi_state[1]), .ZN
       (n_1));
  XNR2D1 g14843__9315(.A1 (ctrl_btn_write_s_db), .A2 (db_write_sync1),
       .ZN (n_0));
  MOAI22D1 inc_add_186_40_g407__9945(.A1 (inc_add_186_40_n_255), .A2
       (timer_cnt[31]), .B1 (inc_add_186_40_n_255), .B2
       (timer_cnt[31]), .ZN (n_449));
  OA21D1 inc_add_186_40_g408__2883(.A1 (inc_add_186_40_n_262), .A2
       (timer_cnt[30]), .B (inc_add_186_40_n_255), .Z (n_450));
  ND2D1 inc_add_186_40_g409__2346(.A1 (inc_add_186_40_n_262), .A2
       (timer_cnt[30]), .ZN (inc_add_186_40_n_255));
  MOAI22D1 inc_add_186_40_g410__1666(.A1 (inc_add_186_40_n_265), .A2
       (timer_cnt[29]), .B1 (inc_add_186_40_n_265), .B2
       (timer_cnt[29]), .ZN (n_451));
  INR2XD0 inc_add_186_40_g411__7410(.A1 (timer_cnt[29]), .B1
       (inc_add_186_40_n_265), .ZN (inc_add_186_40_n_262));
  OA21D1 inc_add_186_40_g412__6417(.A1 (inc_add_186_40_n_272), .A2
       (timer_cnt[28]), .B (inc_add_186_40_n_265), .Z (n_452));
  CKND2D1 inc_add_186_40_g413__5477(.A1 (inc_add_186_40_n_272), .A2
       (timer_cnt[28]), .ZN (inc_add_186_40_n_265));
  MOAI22D1 inc_add_186_40_g414__2398(.A1 (inc_add_186_40_n_275), .A2
       (timer_cnt[27]), .B1 (inc_add_186_40_n_275), .B2
       (timer_cnt[27]), .ZN (n_453));
  INR2XD0 inc_add_186_40_g415__5107(.A1 (timer_cnt[27]), .B1
       (inc_add_186_40_n_275), .ZN (inc_add_186_40_n_272));
  OA21D1 inc_add_186_40_g416__6260(.A1 (inc_add_186_40_n_280), .A2
       (timer_cnt[26]), .B (inc_add_186_40_n_275), .Z (n_454));
  CKND2D1 inc_add_186_40_g417__4319(.A1 (inc_add_186_40_n_280), .A2
       (timer_cnt[26]), .ZN (inc_add_186_40_n_275));
  IAO21D1 inc_add_186_40_g418__8428(.A1 (inc_add_186_40_n_285), .A2
       (timer_cnt[25]), .B (inc_add_186_40_n_280), .ZN (n_455));
  AN2XD1 inc_add_186_40_g419__5526(.A1 (inc_add_186_40_n_285), .A2
       (timer_cnt[25]), .Z (inc_add_186_40_n_280));
  IAO21D1 inc_add_186_40_g420__6783(.A1 (inc_add_186_40_n_292), .A2
       (timer_cnt[24]), .B (inc_add_186_40_n_285), .ZN (n_456));
  AN2XD1 inc_add_186_40_g421__3680(.A1 (inc_add_186_40_n_292), .A2
       (timer_cnt[24]), .Z (inc_add_186_40_n_285));
  MOAI22D1 inc_add_186_40_g422__1617(.A1 (inc_add_186_40_n_295), .A2
       (timer_cnt[23]), .B1 (inc_add_186_40_n_295), .B2
       (timer_cnt[23]), .ZN (n_457));
  INR2XD0 inc_add_186_40_g423__2802(.A1 (timer_cnt[23]), .B1
       (inc_add_186_40_n_295), .ZN (inc_add_186_40_n_292));
  OA21D1 inc_add_186_40_g424__1705(.A1 (inc_add_186_40_n_300), .A2
       (timer_cnt[22]), .B (inc_add_186_40_n_295), .Z (n_458));
  CKND2D1 inc_add_186_40_g425__5122(.A1 (inc_add_186_40_n_300), .A2
       (timer_cnt[22]), .ZN (inc_add_186_40_n_295));
  IAO21D1 inc_add_186_40_g426__8246(.A1 (inc_add_186_40_n_307), .A2
       (timer_cnt[21]), .B (inc_add_186_40_n_300), .ZN (n_459));
  AN2XD1 inc_add_186_40_g427__7098(.A1 (inc_add_186_40_n_307), .A2
       (timer_cnt[21]), .Z (inc_add_186_40_n_300));
  MOAI22D1 inc_add_186_40_g428__6131(.A1 (inc_add_186_40_n_310), .A2
       (timer_cnt[20]), .B1 (inc_add_186_40_n_310), .B2
       (timer_cnt[20]), .ZN (n_460));
  INR2XD0 inc_add_186_40_g429__1881(.A1 (timer_cnt[20]), .B1
       (inc_add_186_40_n_310), .ZN (inc_add_186_40_n_307));
  OA21D1 inc_add_186_40_g430__5115(.A1 (inc_add_186_40_n_315), .A2
       (timer_cnt[19]), .B (inc_add_186_40_n_310), .Z (n_461));
  CKND2D1 inc_add_186_40_g431__7482(.A1 (inc_add_186_40_n_315), .A2
       (timer_cnt[19]), .ZN (inc_add_186_40_n_310));
  IAO21D1 inc_add_186_40_g432__4733(.A1 (inc_add_186_40_n_322), .A2
       (timer_cnt[18]), .B (inc_add_186_40_n_315), .ZN (n_462));
  AN2XD1 inc_add_186_40_g433__6161(.A1 (inc_add_186_40_n_322), .A2
       (timer_cnt[18]), .Z (inc_add_186_40_n_315));
  MOAI22D1 inc_add_186_40_g434__9315(.A1 (inc_add_186_40_n_327), .A2
       (timer_cnt[17]), .B1 (inc_add_186_40_n_327), .B2
       (timer_cnt[17]), .ZN (n_463));
  INR2XD0 inc_add_186_40_g435__9945(.A1 (timer_cnt[17]), .B1
       (inc_add_186_40_n_327), .ZN (inc_add_186_40_n_322));
  MOAI22D1 inc_add_186_40_g436__2883(.A1 (inc_add_186_40_n_330), .A2
       (timer_cnt[16]), .B1 (inc_add_186_40_n_330), .B2
       (timer_cnt[16]), .ZN (n_464));
  IND2D1 inc_add_186_40_g437__2346(.A1 (inc_add_186_40_n_330), .B1
       (timer_cnt[16]), .ZN (inc_add_186_40_n_327));
  OA21D1 inc_add_186_40_g438__1666(.A1 (inc_add_186_40_n_335), .A2
       (timer_cnt[15]), .B (inc_add_186_40_n_330), .Z (n_465));
  CKND2D1 inc_add_186_40_g439__7410(.A1 (inc_add_186_40_n_335), .A2
       (timer_cnt[15]), .ZN (inc_add_186_40_n_330));
  IAO21D1 inc_add_186_40_g440__6417(.A1 (inc_add_186_40_n_342), .A2
       (timer_cnt[14]), .B (inc_add_186_40_n_335), .ZN (n_466));
  AN2XD1 inc_add_186_40_g441__5477(.A1 (inc_add_186_40_n_342), .A2
       (timer_cnt[14]), .Z (inc_add_186_40_n_335));
  MOAI22D1 inc_add_186_40_g442__2398(.A1 (inc_add_186_40_n_345), .A2
       (timer_cnt[13]), .B1 (inc_add_186_40_n_345), .B2
       (timer_cnt[13]), .ZN (n_467));
  INR2XD0 inc_add_186_40_g443__5107(.A1 (timer_cnt[13]), .B1
       (inc_add_186_40_n_345), .ZN (inc_add_186_40_n_342));
  OA21D1 inc_add_186_40_g444__6260(.A1 (inc_add_186_40_n_352), .A2
       (timer_cnt[12]), .B (inc_add_186_40_n_345), .Z (n_468));
  CKND2D1 inc_add_186_40_g445__4319(.A1 (inc_add_186_40_n_352), .A2
       (timer_cnt[12]), .ZN (inc_add_186_40_n_345));
  MOAI22D1 inc_add_186_40_g446__8428(.A1 (inc_add_186_40_n_355), .A2
       (timer_cnt[11]), .B1 (inc_add_186_40_n_355), .B2
       (timer_cnt[11]), .ZN (n_469));
  INR2XD0 inc_add_186_40_g447__5526(.A1 (timer_cnt[11]), .B1
       (inc_add_186_40_n_355), .ZN (inc_add_186_40_n_352));
  OA21D1 inc_add_186_40_g448__6783(.A1 (inc_add_186_40_n_360), .A2
       (timer_cnt[10]), .B (inc_add_186_40_n_355), .Z (n_470));
  CKND2D1 inc_add_186_40_g449__3680(.A1 (inc_add_186_40_n_360), .A2
       (timer_cnt[10]), .ZN (inc_add_186_40_n_355));
  IAO21D1 inc_add_186_40_g450__1617(.A1 (inc_add_186_40_n_367), .A2
       (timer_cnt[9]), .B (inc_add_186_40_n_360), .ZN (n_471));
  AN2XD1 inc_add_186_40_g451__2802(.A1 (inc_add_186_40_n_367), .A2
       (timer_cnt[9]), .Z (inc_add_186_40_n_360));
  MOAI22D1 inc_add_186_40_g452__1705(.A1 (inc_add_186_40_n_370), .A2
       (timer_cnt[8]), .B1 (inc_add_186_40_n_370), .B2 (timer_cnt[8]),
       .ZN (n_472));
  INR2XD0 inc_add_186_40_g453__5122(.A1 (timer_cnt[8]), .B1
       (inc_add_186_40_n_370), .ZN (inc_add_186_40_n_367));
  OA21D1 inc_add_186_40_g454__8246(.A1 (inc_add_186_40_n_375), .A2
       (timer_cnt[7]), .B (inc_add_186_40_n_370), .Z (n_473));
  CKND2D1 inc_add_186_40_g455__7098(.A1 (inc_add_186_40_n_375), .A2
       (timer_cnt[7]), .ZN (inc_add_186_40_n_370));
  IAO21D1 inc_add_186_40_g456__6131(.A1 (inc_add_186_40_n_382), .A2
       (timer_cnt[6]), .B (inc_add_186_40_n_375), .ZN (n_474));
  AN2XD1 inc_add_186_40_g457__1881(.A1 (inc_add_186_40_n_382), .A2
       (timer_cnt[6]), .Z (inc_add_186_40_n_375));
  MOAI22D1 inc_add_186_40_g458__5115(.A1 (inc_add_186_40_n_385), .A2
       (timer_cnt[5]), .B1 (inc_add_186_40_n_385), .B2 (timer_cnt[5]),
       .ZN (n_475));
  INR2XD0 inc_add_186_40_g459__7482(.A1 (timer_cnt[5]), .B1
       (inc_add_186_40_n_385), .ZN (inc_add_186_40_n_382));
  OA21D1 inc_add_186_40_g460__4733(.A1 (inc_add_186_40_n_390), .A2
       (timer_cnt[4]), .B (inc_add_186_40_n_385), .Z (n_476));
  CKND2D1 inc_add_186_40_g461__6161(.A1 (inc_add_186_40_n_390), .A2
       (timer_cnt[4]), .ZN (inc_add_186_40_n_385));
  IAO21D1 inc_add_186_40_g462__9315(.A1 (inc_add_186_40_n_395), .A2
       (timer_cnt[3]), .B (inc_add_186_40_n_390), .ZN (n_477));
  AN2XD1 inc_add_186_40_g463__9945(.A1 (inc_add_186_40_n_395), .A2
       (timer_cnt[3]), .Z (inc_add_186_40_n_390));
  IAO21D1 inc_add_186_40_g464__2883(.A1 (inc_add_186_40_n_400), .A2
       (timer_cnt[2]), .B (inc_add_186_40_n_395), .ZN (n_478));
  AN2XD1 inc_add_186_40_g465__2346(.A1 (inc_add_186_40_n_400), .A2
       (timer_cnt[2]), .Z (inc_add_186_40_n_395));
  IAO21D1 inc_add_186_40_g466__1666(.A1 (timer_cnt[0]), .A2
       (timer_cnt[1]), .B (inc_add_186_40_n_400), .ZN (n_479));
  AN2XD1 inc_add_186_40_g467__7410(.A1 (timer_cnt[0]), .A2
       (timer_cnt[1]), .Z (inc_add_186_40_n_400));
  MOAI22D1 inc_add_113_46_g283__6417(.A1 (inc_add_113_46_n_237), .A2
       (db_write_cnt[17]), .B1 (inc_add_113_46_n_237), .B2
       (db_write_cnt[17]), .ZN (n_427));
  MOAI22D1 inc_add_113_46_g285__5477(.A1 (inc_add_113_46_n_240), .A2
       (db_write_cnt[16]), .B1 (inc_add_113_46_n_240), .B2
       (db_write_cnt[16]), .ZN (n_426));
  IND2D1 inc_add_113_46_g286__2398(.A1 (inc_add_113_46_n_240), .B1
       (db_write_cnt[16]), .ZN (inc_add_113_46_n_237));
  OA21D1 inc_add_113_46_g287__5107(.A1 (inc_add_113_46_n_245), .A2
       (db_write_cnt[15]), .B (inc_add_113_46_n_240), .Z (n_425));
  CKND2D1 inc_add_113_46_g288__6260(.A1 (inc_add_113_46_n_245), .A2
       (db_write_cnt[15]), .ZN (inc_add_113_46_n_240));
  IAO21D1 inc_add_113_46_g289__4319(.A1 (inc_add_113_46_n_252), .A2
       (db_write_cnt[14]), .B (inc_add_113_46_n_245), .ZN (n_424));
  AN2XD1 inc_add_113_46_g290__8428(.A1 (inc_add_113_46_n_252), .A2
       (db_write_cnt[14]), .Z (inc_add_113_46_n_245));
  MOAI22D1 inc_add_113_46_g291__5526(.A1 (inc_add_113_46_n_255), .A2
       (db_write_cnt[13]), .B1 (inc_add_113_46_n_255), .B2
       (db_write_cnt[13]), .ZN (n_423));
  INR2XD0 inc_add_113_46_g292__6783(.A1 (db_write_cnt[13]), .B1
       (inc_add_113_46_n_255), .ZN (inc_add_113_46_n_252));
  OA21D1 inc_add_113_46_g293__3680(.A1 (inc_add_113_46_n_262), .A2
       (db_write_cnt[12]), .B (inc_add_113_46_n_255), .Z (n_422));
  CKND2D1 inc_add_113_46_g294__1617(.A1 (inc_add_113_46_n_262), .A2
       (db_write_cnt[12]), .ZN (inc_add_113_46_n_255));
  MOAI22D1 inc_add_113_46_g295__2802(.A1 (inc_add_113_46_n_265), .A2
       (db_write_cnt[11]), .B1 (inc_add_113_46_n_265), .B2
       (db_write_cnt[11]), .ZN (n_421));
  INR2XD0 inc_add_113_46_g296__1705(.A1 (db_write_cnt[11]), .B1
       (inc_add_113_46_n_265), .ZN (inc_add_113_46_n_262));
  OA21D1 inc_add_113_46_g297__5122(.A1 (inc_add_113_46_n_270), .A2
       (db_write_cnt[10]), .B (inc_add_113_46_n_265), .Z (n_420));
  CKND2D1 inc_add_113_46_g298__8246(.A1 (inc_add_113_46_n_270), .A2
       (db_write_cnt[10]), .ZN (inc_add_113_46_n_265));
  IAO21D1 inc_add_113_46_g299__7098(.A1 (inc_add_113_46_n_277), .A2
       (db_write_cnt[9]), .B (inc_add_113_46_n_270), .ZN (n_419));
  AN2XD1 inc_add_113_46_g300__6131(.A1 (inc_add_113_46_n_277), .A2
       (db_write_cnt[9]), .Z (inc_add_113_46_n_270));
  MOAI22D1 inc_add_113_46_g301__1881(.A1 (inc_add_113_46_n_280), .A2
       (db_write_cnt[8]), .B1 (inc_add_113_46_n_280), .B2
       (db_write_cnt[8]), .ZN (n_418));
  INR2XD0 inc_add_113_46_g302__5115(.A1 (db_write_cnt[8]), .B1
       (inc_add_113_46_n_280), .ZN (inc_add_113_46_n_277));
  OA21D1 inc_add_113_46_g303__7482(.A1 (inc_add_113_46_n_285), .A2
       (db_write_cnt[7]), .B (inc_add_113_46_n_280), .Z (n_417));
  CKND2D1 inc_add_113_46_g304__4733(.A1 (inc_add_113_46_n_285), .A2
       (db_write_cnt[7]), .ZN (inc_add_113_46_n_280));
  IAO21D1 inc_add_113_46_g305__6161(.A1 (inc_add_113_46_n_292), .A2
       (db_write_cnt[6]), .B (inc_add_113_46_n_285), .ZN (n_416));
  AN2XD1 inc_add_113_46_g306__9315(.A1 (inc_add_113_46_n_292), .A2
       (db_write_cnt[6]), .Z (inc_add_113_46_n_285));
  MOAI22D1 inc_add_113_46_g307__9945(.A1 (inc_add_113_46_n_295), .A2
       (db_write_cnt[5]), .B1 (inc_add_113_46_n_295), .B2
       (db_write_cnt[5]), .ZN (n_415));
  INR2XD0 inc_add_113_46_g308__2883(.A1 (db_write_cnt[5]), .B1
       (inc_add_113_46_n_295), .ZN (inc_add_113_46_n_292));
  OA21D1 inc_add_113_46_g309__2346(.A1 (inc_add_113_46_n_300), .A2
       (db_write_cnt[4]), .B (inc_add_113_46_n_295), .Z (n_414));
  CKND2D1 inc_add_113_46_g310__1666(.A1 (inc_add_113_46_n_300), .A2
       (db_write_cnt[4]), .ZN (inc_add_113_46_n_295));
  IAO21D1 inc_add_113_46_g311__7410(.A1 (inc_add_113_46_n_305), .A2
       (db_write_cnt[3]), .B (inc_add_113_46_n_300), .ZN (n_413));
  AN2XD1 inc_add_113_46_g312__6417(.A1 (inc_add_113_46_n_305), .A2
       (db_write_cnt[3]), .Z (inc_add_113_46_n_300));
  IAO21D1 inc_add_113_46_g313__5477(.A1 (inc_add_113_46_n_310), .A2
       (db_write_cnt[2]), .B (inc_add_113_46_n_305), .ZN (n_412));
  AN2XD1 inc_add_113_46_g314__2398(.A1 (inc_add_113_46_n_310), .A2
       (db_write_cnt[2]), .Z (inc_add_113_46_n_305));
  IAO21D1 inc_add_113_46_g315__5107(.A1 (db_write_cnt[0]), .A2
       (db_write_cnt[1]), .B (inc_add_113_46_n_310), .ZN (n_411));
  AN2XD1 inc_add_113_46_g316__6260(.A1 (db_write_cnt[0]), .A2
       (db_write_cnt[1]), .Z (inc_add_113_46_n_310));
  MOAI22D1 inc_add_153_44_g283__4319(.A1 (inc_add_153_44_n_237), .A2
       (db_read_cnt[17]), .B1 (inc_add_153_44_n_237), .B2
       (db_read_cnt[17]), .ZN (n_445));
  MOAI22D1 inc_add_153_44_g285__8428(.A1 (inc_add_153_44_n_240), .A2
       (db_read_cnt[16]), .B1 (inc_add_153_44_n_240), .B2
       (db_read_cnt[16]), .ZN (n_444));
  IND2D1 inc_add_153_44_g286__5526(.A1 (inc_add_153_44_n_240), .B1
       (db_read_cnt[16]), .ZN (inc_add_153_44_n_237));
  OA21D1 inc_add_153_44_g287__6783(.A1 (inc_add_153_44_n_245), .A2
       (db_read_cnt[15]), .B (inc_add_153_44_n_240), .Z (n_443));
  CKND2D1 inc_add_153_44_g288__3680(.A1 (inc_add_153_44_n_245), .A2
       (db_read_cnt[15]), .ZN (inc_add_153_44_n_240));
  IAO21D1 inc_add_153_44_g289__1617(.A1 (inc_add_153_44_n_252), .A2
       (db_read_cnt[14]), .B (inc_add_153_44_n_245), .ZN (n_442));
  AN2XD1 inc_add_153_44_g290__2802(.A1 (inc_add_153_44_n_252), .A2
       (db_read_cnt[14]), .Z (inc_add_153_44_n_245));
  MOAI22D1 inc_add_153_44_g291__1705(.A1 (inc_add_153_44_n_255), .A2
       (db_read_cnt[13]), .B1 (inc_add_153_44_n_255), .B2
       (db_read_cnt[13]), .ZN (n_441));
  INR2XD0 inc_add_153_44_g292__5122(.A1 (db_read_cnt[13]), .B1
       (inc_add_153_44_n_255), .ZN (inc_add_153_44_n_252));
  OA21D1 inc_add_153_44_g293__8246(.A1 (inc_add_153_44_n_262), .A2
       (db_read_cnt[12]), .B (inc_add_153_44_n_255), .Z (n_440));
  CKND2D1 inc_add_153_44_g294__7098(.A1 (inc_add_153_44_n_262), .A2
       (db_read_cnt[12]), .ZN (inc_add_153_44_n_255));
  MOAI22D1 inc_add_153_44_g295__6131(.A1 (inc_add_153_44_n_265), .A2
       (db_read_cnt[11]), .B1 (inc_add_153_44_n_265), .B2
       (db_read_cnt[11]), .ZN (n_439));
  INR2XD0 inc_add_153_44_g296__1881(.A1 (db_read_cnt[11]), .B1
       (inc_add_153_44_n_265), .ZN (inc_add_153_44_n_262));
  OA21D1 inc_add_153_44_g297__5115(.A1 (inc_add_153_44_n_270), .A2
       (db_read_cnt[10]), .B (inc_add_153_44_n_265), .Z (n_438));
  CKND2D1 inc_add_153_44_g298__7482(.A1 (inc_add_153_44_n_270), .A2
       (db_read_cnt[10]), .ZN (inc_add_153_44_n_265));
  IAO21D1 inc_add_153_44_g299__4733(.A1 (inc_add_153_44_n_277), .A2
       (db_read_cnt[9]), .B (inc_add_153_44_n_270), .ZN (n_437));
  AN2XD1 inc_add_153_44_g300__6161(.A1 (inc_add_153_44_n_277), .A2
       (db_read_cnt[9]), .Z (inc_add_153_44_n_270));
  MOAI22D1 inc_add_153_44_g301__9315(.A1 (inc_add_153_44_n_280), .A2
       (db_read_cnt[8]), .B1 (inc_add_153_44_n_280), .B2
       (db_read_cnt[8]), .ZN (n_436));
  INR2XD0 inc_add_153_44_g302__9945(.A1 (db_read_cnt[8]), .B1
       (inc_add_153_44_n_280), .ZN (inc_add_153_44_n_277));
  OA21D1 inc_add_153_44_g303__2883(.A1 (inc_add_153_44_n_285), .A2
       (db_read_cnt[7]), .B (inc_add_153_44_n_280), .Z (n_435));
  CKND2D1 inc_add_153_44_g304__2346(.A1 (inc_add_153_44_n_285), .A2
       (db_read_cnt[7]), .ZN (inc_add_153_44_n_280));
  IAO21D1 inc_add_153_44_g305__1666(.A1 (inc_add_153_44_n_292), .A2
       (db_read_cnt[6]), .B (inc_add_153_44_n_285), .ZN (n_434));
  AN2XD1 inc_add_153_44_g306__7410(.A1 (inc_add_153_44_n_292), .A2
       (db_read_cnt[6]), .Z (inc_add_153_44_n_285));
  MOAI22D1 inc_add_153_44_g307__6417(.A1 (inc_add_153_44_n_295), .A2
       (db_read_cnt[5]), .B1 (inc_add_153_44_n_295), .B2
       (db_read_cnt[5]), .ZN (n_433));
  INR2XD0 inc_add_153_44_g308__5477(.A1 (db_read_cnt[5]), .B1
       (inc_add_153_44_n_295), .ZN (inc_add_153_44_n_292));
  OA21D1 inc_add_153_44_g309__2398(.A1 (inc_add_153_44_n_300), .A2
       (db_read_cnt[4]), .B (inc_add_153_44_n_295), .Z (n_432));
  CKND2D1 inc_add_153_44_g310__5107(.A1 (inc_add_153_44_n_300), .A2
       (db_read_cnt[4]), .ZN (inc_add_153_44_n_295));
  IAO21D1 inc_add_153_44_g311__6260(.A1 (inc_add_153_44_n_305), .A2
       (db_read_cnt[3]), .B (inc_add_153_44_n_300), .ZN (n_431));
  AN2XD1 inc_add_153_44_g312__4319(.A1 (inc_add_153_44_n_305), .A2
       (db_read_cnt[3]), .Z (inc_add_153_44_n_300));
  IAO21D1 inc_add_153_44_g313__8428(.A1 (inc_add_153_44_n_310), .A2
       (db_read_cnt[2]), .B (inc_add_153_44_n_305), .ZN (n_430));
  AN2XD1 inc_add_153_44_g314__5526(.A1 (inc_add_153_44_n_310), .A2
       (db_read_cnt[2]), .Z (inc_add_153_44_n_305));
  IAO21D1 inc_add_153_44_g315__6783(.A1 (db_read_cnt[0]), .A2
       (db_read_cnt[1]), .B (inc_add_153_44_n_310), .ZN (n_429));
  AN2XD1 inc_add_153_44_g316__3680(.A1 (db_read_cnt[0]), .A2
       (db_read_cnt[1]), .Z (inc_add_153_44_n_310));
  MOAI22D1 inc_add_73_46_g283__1617(.A1 (inc_add_73_46_n_237), .A2
       (db_latch_cnt[17]), .B1 (inc_add_73_46_n_237), .B2
       (db_latch_cnt[17]), .ZN (n_409));
  MOAI22D1 inc_add_73_46_g285__2802(.A1 (inc_add_73_46_n_240), .A2
       (db_latch_cnt[16]), .B1 (inc_add_73_46_n_240), .B2
       (db_latch_cnt[16]), .ZN (n_408));
  IND2D1 inc_add_73_46_g286__1705(.A1 (inc_add_73_46_n_240), .B1
       (db_latch_cnt[16]), .ZN (inc_add_73_46_n_237));
  OA21D1 inc_add_73_46_g287__5122(.A1 (inc_add_73_46_n_245), .A2
       (db_latch_cnt[15]), .B (inc_add_73_46_n_240), .Z (n_407));
  CKND2D1 inc_add_73_46_g288__8246(.A1 (inc_add_73_46_n_245), .A2
       (db_latch_cnt[15]), .ZN (inc_add_73_46_n_240));
  IAO21D1 inc_add_73_46_g289__7098(.A1 (inc_add_73_46_n_252), .A2
       (db_latch_cnt[14]), .B (inc_add_73_46_n_245), .ZN (n_406));
  AN2XD1 inc_add_73_46_g290__6131(.A1 (inc_add_73_46_n_252), .A2
       (db_latch_cnt[14]), .Z (inc_add_73_46_n_245));
  MOAI22D1 inc_add_73_46_g291__1881(.A1 (inc_add_73_46_n_255), .A2
       (db_latch_cnt[13]), .B1 (inc_add_73_46_n_255), .B2
       (db_latch_cnt[13]), .ZN (n_405));
  INR2XD0 inc_add_73_46_g292__5115(.A1 (db_latch_cnt[13]), .B1
       (inc_add_73_46_n_255), .ZN (inc_add_73_46_n_252));
  OA21D1 inc_add_73_46_g293__7482(.A1 (inc_add_73_46_n_262), .A2
       (db_latch_cnt[12]), .B (inc_add_73_46_n_255), .Z (n_404));
  CKND2D1 inc_add_73_46_g294__4733(.A1 (inc_add_73_46_n_262), .A2
       (db_latch_cnt[12]), .ZN (inc_add_73_46_n_255));
  MOAI22D1 inc_add_73_46_g295__6161(.A1 (inc_add_73_46_n_265), .A2
       (db_latch_cnt[11]), .B1 (inc_add_73_46_n_265), .B2
       (db_latch_cnt[11]), .ZN (n_403));
  INR2XD0 inc_add_73_46_g296__9315(.A1 (db_latch_cnt[11]), .B1
       (inc_add_73_46_n_265), .ZN (inc_add_73_46_n_262));
  OA21D1 inc_add_73_46_g297__9945(.A1 (inc_add_73_46_n_270), .A2
       (db_latch_cnt[10]), .B (inc_add_73_46_n_265), .Z (n_402));
  CKND2D1 inc_add_73_46_g298__2883(.A1 (inc_add_73_46_n_270), .A2
       (db_latch_cnt[10]), .ZN (inc_add_73_46_n_265));
  IAO21D1 inc_add_73_46_g299__2346(.A1 (inc_add_73_46_n_277), .A2
       (db_latch_cnt[9]), .B (inc_add_73_46_n_270), .ZN (n_401));
  AN2XD1 inc_add_73_46_g300__1666(.A1 (inc_add_73_46_n_277), .A2
       (db_latch_cnt[9]), .Z (inc_add_73_46_n_270));
  MOAI22D1 inc_add_73_46_g301__7410(.A1 (inc_add_73_46_n_280), .A2
       (db_latch_cnt[8]), .B1 (inc_add_73_46_n_280), .B2
       (db_latch_cnt[8]), .ZN (n_400));
  INR2XD0 inc_add_73_46_g302__6417(.A1 (db_latch_cnt[8]), .B1
       (inc_add_73_46_n_280), .ZN (inc_add_73_46_n_277));
  OA21D1 inc_add_73_46_g303__5477(.A1 (inc_add_73_46_n_285), .A2
       (db_latch_cnt[7]), .B (inc_add_73_46_n_280), .Z (n_399));
  CKND2D1 inc_add_73_46_g304__2398(.A1 (inc_add_73_46_n_285), .A2
       (db_latch_cnt[7]), .ZN (inc_add_73_46_n_280));
  IAO21D1 inc_add_73_46_g305__5107(.A1 (inc_add_73_46_n_292), .A2
       (db_latch_cnt[6]), .B (inc_add_73_46_n_285), .ZN (n_398));
  AN2XD1 inc_add_73_46_g306__6260(.A1 (inc_add_73_46_n_292), .A2
       (db_latch_cnt[6]), .Z (inc_add_73_46_n_285));
  MOAI22D1 inc_add_73_46_g307__4319(.A1 (inc_add_73_46_n_295), .A2
       (db_latch_cnt[5]), .B1 (inc_add_73_46_n_295), .B2
       (db_latch_cnt[5]), .ZN (n_397));
  INR2XD0 inc_add_73_46_g308__8428(.A1 (db_latch_cnt[5]), .B1
       (inc_add_73_46_n_295), .ZN (inc_add_73_46_n_292));
  OA21D1 inc_add_73_46_g309__5526(.A1 (inc_add_73_46_n_300), .A2
       (db_latch_cnt[4]), .B (inc_add_73_46_n_295), .Z (n_396));
  CKND2D1 inc_add_73_46_g310__6783(.A1 (inc_add_73_46_n_300), .A2
       (db_latch_cnt[4]), .ZN (inc_add_73_46_n_295));
  IAO21D1 inc_add_73_46_g311__3680(.A1 (inc_add_73_46_n_305), .A2
       (db_latch_cnt[3]), .B (inc_add_73_46_n_300), .ZN (n_395));
  AN2XD1 inc_add_73_46_g312__1617(.A1 (inc_add_73_46_n_305), .A2
       (db_latch_cnt[3]), .Z (inc_add_73_46_n_300));
  IAO21D1 inc_add_73_46_g313__2802(.A1 (inc_add_73_46_n_310), .A2
       (db_latch_cnt[2]), .B (inc_add_73_46_n_305), .ZN (n_394));
  AN2XD1 inc_add_73_46_g314__1705(.A1 (inc_add_73_46_n_310), .A2
       (db_latch_cnt[2]), .Z (inc_add_73_46_n_305));
  IAO21D1 inc_add_73_46_g315__5122(.A1 (db_latch_cnt[0]), .A2
       (db_latch_cnt[1]), .B (inc_add_73_46_n_310), .ZN (n_393));
  AN2XD1 inc_add_73_46_g316__8246(.A1 (db_latch_cnt[0]), .A2
       (db_latch_cnt[1]), .Z (inc_add_73_46_n_310));
  ND3D1 g2(.A1 (n_272), .A2 (db_latch_cnt[16]), .A3 (db_latch_cnt[17]),
       .ZN (n_484));
  ND3D1 g14844(.A1 (n_271), .A2 (db_read_cnt[16]), .A3
       (db_read_cnt[17]), .ZN (n_485));
  ND3D1 g14845(.A1 (n_270), .A2 (db_write_cnt[16]), .A3
       (db_write_cnt[17]), .ZN (n_486));
  TIEL tie_0_cell(.ZN (RGB1[2]));
endmodule

