
//input ports
add mapped point clk clk -type PI PI
add mapped point sw[15] sw[15] -type PI PI
add mapped point sw[14] sw[14] -type PI PI
add mapped point sw[13] sw[13] -type PI PI
add mapped point sw[12] sw[12] -type PI PI
add mapped point sw[11] sw[11] -type PI PI
add mapped point sw[10] sw[10] -type PI PI
add mapped point sw[9] sw[9] -type PI PI
add mapped point sw[8] sw[8] -type PI PI
add mapped point sw[7] sw[7] -type PI PI
add mapped point sw[6] sw[6] -type PI PI
add mapped point sw[5] sw[5] -type PI PI
add mapped point sw[4] sw[4] -type PI PI
add mapped point sw[3] sw[3] -type PI PI
add mapped point sw[2] sw[2] -type PI PI
add mapped point sw[1] sw[1] -type PI PI
add mapped point sw[0] sw[0] -type PI PI
add mapped point btn[3] btn[3] -type PI PI
add mapped point btn[2] btn[2] -type PI PI
add mapped point btn[1] btn[1] -type PI PI
add mapped point btn[0] btn[0] -type PI PI
add mapped point spi_miso_in spi_miso_in -type PI PI

//output ports
add mapped point led[15] led[15] -type PO PO
add mapped point led[14] led[14] -type PO PO
add mapped point led[13] led[13] -type PO PO
add mapped point led[12] led[12] -type PO PO
add mapped point led[11] led[11] -type PO PO
add mapped point led[10] led[10] -type PO PO
add mapped point led[9] led[9] -type PO PO
add mapped point led[8] led[8] -type PO PO
add mapped point led[7] led[7] -type PO PO
add mapped point led[6] led[6] -type PO PO
add mapped point led[5] led[5] -type PO PO
add mapped point led[4] led[4] -type PO PO
add mapped point led[3] led[3] -type PO PO
add mapped point led[2] led[2] -type PO PO
add mapped point led[1] led[1] -type PO PO
add mapped point led[0] led[0] -type PO PO
add mapped point RGB0[2] RGB0[2] -type PO PO
add mapped point RGB0[1] RGB0[1] -type PO PO
add mapped point RGB0[0] RGB0[0] -type PO PO
add mapped point RGB1[2] RGB1[2] -type PO PO
add mapped point RGB1[1] RGB1[1] -type PO PO
add mapped point RGB1[0] RGB1[0] -type PO PO
add mapped point spi_sclk_out spi_sclk_out -type PO PO
add mapped point spi_mosi_out spi_mosi_out -type PO PO
add mapped point spi_cs_n_out[7] spi_cs_n_out[7] -type PO PO
add mapped point spi_cs_n_out[6] spi_cs_n_out[6] -type PO PO
add mapped point spi_cs_n_out[5] spi_cs_n_out[5] -type PO PO
add mapped point spi_cs_n_out[4] spi_cs_n_out[4] -type PO PO
add mapped point spi_cs_n_out[3] spi_cs_n_out[3] -type PO PO
add mapped point spi_cs_n_out[2] spi_cs_n_out[2] -type PO PO
add mapped point spi_cs_n_out[1] spi_cs_n_out[1] -type PO PO
add mapped point spi_cs_n_out[0] spi_cs_n_out[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point ctrl_timer_done/q ctrl_timer_done_reg/Q -type DFF DFF
add mapped point led_green_write_wire/q led_green_write_wire_reg/Q -type DFF DFF
add mapped point ctrl_timer_start/q ctrl_timer_start_reg/Q -type DFF DFF
add mapped point master_start_tx/q master_start_tx_reg/Q -type DFF DFF
add mapped point master_tx_done/q master_tx_done_reg/Q -type DFF DFF
add mapped point db_write_sync1/q db_write_sync1_reg/Q -type DFF DFF
add mapped point db_read_sync1/q db_read_sync1_reg/Q -type DFF DFF
add mapped point db_latch_sync1/q db_latch_sync1_reg/Q -type DFF DFF
add mapped point db_read_sync0/q db_read_sync0_reg/Q -type DFF DFF
add mapped point db_write_sync0/q db_write_sync0_reg/Q -type DFF DFF
add mapped point db_latch_sync0/q db_latch_sync0_reg/Q -type DFF DFF
add mapped point ctrl_btn_latch_db/q ctrl_btn_latch_db_reg/Q -type DFF DFF
add mapped point ctrl_btn_read_s_db/q ctrl_btn_read_s_db_reg/Q -type DFF DFF
add mapped point ctrl_btn_write_s_db/q ctrl_btn_write_s_db_reg/Q -type DFF DFF
add mapped point ctrl_gw_idx[0]/q ctrl_gw_idx_reg[0]/Q -type DFF DFF
add mapped point ctrl_gw_idx[1]/q ctrl_gw_idx_reg[1]/Q -type DFF DFF
add mapped point ctrl_gw_idx[2]/q ctrl_gw_idx_reg[2]/Q -type DFF DFF
add mapped point ctrl_last_op_was_write/q ctrl_last_op_was_write_reg/Q -type DFF DFF
add mapped point ctrl_latched_addr[0]/q ctrl_latched_addr_reg[0]/Q -type DFF DFF
add mapped point ctrl_latched_addr[1]/q ctrl_latched_addr_reg[1]/Q -type DFF DFF
add mapped point ctrl_latched_addr[2]/q ctrl_latched_addr_reg[2]/Q -type DFF DFF
add mapped point ctrl_latched_addr[3]/q ctrl_latched_addr_reg[3]/Q -type DFF DFF
add mapped point ctrl_latched_addr[4]/q ctrl_latched_addr_reg[4]/Q -type DFF DFF
add mapped point ctrl_latched_addr[5]/q ctrl_latched_addr_reg[5]/Q -type DFF DFF
add mapped point ctrl_latched_addr[6]/q ctrl_latched_addr_reg[6]/Q -type DFF DFF
add mapped point ctrl_latched_addr[7]/q ctrl_latched_addr_reg[7]/Q -type DFF DFF
add mapped point ctrl_latched_global/q ctrl_latched_global_reg/Q -type DFF DFF
add mapped point ctrl_latched_id[0]/q ctrl_latched_id_reg[0]/Q -type DFF DFF
add mapped point ctrl_latched_id[1]/q ctrl_latched_id_reg[1]/Q -type DFF DFF
add mapped point ctrl_latched_id[2]/q ctrl_latched_id_reg[2]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[0]/q ctrl_latched_write_data_reg[0]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[1]/q ctrl_latched_write_data_reg[1]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[2]/q ctrl_latched_write_data_reg[2]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[3]/q ctrl_latched_write_data_reg[3]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[4]/q ctrl_latched_write_data_reg[4]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[5]/q ctrl_latched_write_data_reg[5]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[6]/q ctrl_latched_write_data_reg[6]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[7]/q ctrl_latched_write_data_reg[7]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[8]/q ctrl_latched_write_data_reg[8]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[9]/q ctrl_latched_write_data_reg[9]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[10]/q ctrl_latched_write_data_reg[10]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[11]/q ctrl_latched_write_data_reg[11]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[12]/q ctrl_latched_write_data_reg[12]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[13]/q ctrl_latched_write_data_reg[13]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[14]/q ctrl_latched_write_data_reg[14]/Q -type DFF DFF
add mapped point ctrl_latched_write_data[15]/q ctrl_latched_write_data_reg[15]/Q -type DFF DFF
add mapped point ctrl_state[0]/q ctrl_state_reg[0]/Q -type DFF DFF
add mapped point ctrl_state[1]/q ctrl_state_reg[1]/Q -type DFF DFF
add mapped point ctrl_state[2]/q ctrl_state_reg[2]/Q -type DFF DFF
add mapped point ctrl_state[3]/q ctrl_state_reg[3]/Q -type DFF DFF
add mapped point db_latch_cnt[0]/q db_latch_cnt_reg[0]/Q -type DFF DFF
add mapped point db_latch_cnt[1]/q db_latch_cnt_reg[1]/Q -type DFF DFF
add mapped point db_latch_cnt[2]/q db_latch_cnt_reg[2]/Q -type DFF DFF
add mapped point db_latch_cnt[3]/q db_latch_cnt_reg[3]/Q -type DFF DFF
add mapped point db_latch_cnt[4]/q db_latch_cnt_reg[4]/Q -type DFF DFF
add mapped point db_latch_cnt[5]/q db_latch_cnt_reg[5]/Q -type DFF DFF
add mapped point db_latch_cnt[6]/q db_latch_cnt_reg[6]/Q -type DFF DFF
add mapped point db_latch_cnt[7]/q db_latch_cnt_reg[7]/Q -type DFF DFF
add mapped point db_latch_cnt[8]/q db_latch_cnt_reg[8]/Q -type DFF DFF
add mapped point db_latch_cnt[9]/q db_latch_cnt_reg[9]/Q -type DFF DFF
add mapped point db_latch_cnt[10]/q db_latch_cnt_reg[10]/Q -type DFF DFF
add mapped point db_latch_cnt[11]/q db_latch_cnt_reg[11]/Q -type DFF DFF
add mapped point db_latch_cnt[12]/q db_latch_cnt_reg[12]/Q -type DFF DFF
add mapped point db_latch_cnt[13]/q db_latch_cnt_reg[13]/Q -type DFF DFF
add mapped point db_latch_cnt[14]/q db_latch_cnt_reg[14]/Q -type DFF DFF
add mapped point db_latch_cnt[15]/q db_latch_cnt_reg[15]/Q -type DFF DFF
add mapped point db_latch_cnt[16]/q db_latch_cnt_reg[16]/Q -type DFF DFF
add mapped point db_latch_cnt[17]/q db_latch_cnt_reg[17]/Q -type DFF DFF
add mapped point db_latch_cnt[18]/q db_latch_cnt_reg[18]/Q -type DFF DFF
add mapped point db_read_cnt[0]/q db_read_cnt_reg[0]/Q -type DFF DFF
add mapped point db_read_cnt[1]/q db_read_cnt_reg[1]/Q -type DFF DFF
add mapped point db_read_cnt[2]/q db_read_cnt_reg[2]/Q -type DFF DFF
add mapped point db_read_cnt[3]/q db_read_cnt_reg[3]/Q -type DFF DFF
add mapped point db_read_cnt[4]/q db_read_cnt_reg[4]/Q -type DFF DFF
add mapped point db_read_cnt[5]/q db_read_cnt_reg[5]/Q -type DFF DFF
add mapped point db_read_cnt[6]/q db_read_cnt_reg[6]/Q -type DFF DFF
add mapped point db_read_cnt[7]/q db_read_cnt_reg[7]/Q -type DFF DFF
add mapped point db_read_cnt[8]/q db_read_cnt_reg[8]/Q -type DFF DFF
add mapped point db_read_cnt[9]/q db_read_cnt_reg[9]/Q -type DFF DFF
add mapped point db_read_cnt[10]/q db_read_cnt_reg[10]/Q -type DFF DFF
add mapped point db_read_cnt[11]/q db_read_cnt_reg[11]/Q -type DFF DFF
add mapped point db_read_cnt[12]/q db_read_cnt_reg[12]/Q -type DFF DFF
add mapped point db_read_cnt[13]/q db_read_cnt_reg[13]/Q -type DFF DFF
add mapped point db_read_cnt[14]/q db_read_cnt_reg[14]/Q -type DFF DFF
add mapped point db_read_cnt[15]/q db_read_cnt_reg[15]/Q -type DFF DFF
add mapped point db_read_cnt[16]/q db_read_cnt_reg[16]/Q -type DFF DFF
add mapped point db_read_cnt[17]/q db_read_cnt_reg[17]/Q -type DFF DFF
add mapped point db_read_cnt[18]/q db_read_cnt_reg[18]/Q -type DFF DFF
add mapped point db_write_cnt[0]/q db_write_cnt_reg[0]/Q -type DFF DFF
add mapped point db_write_cnt[1]/q db_write_cnt_reg[1]/Q -type DFF DFF
add mapped point db_write_cnt[2]/q db_write_cnt_reg[2]/Q -type DFF DFF
add mapped point db_write_cnt[3]/q db_write_cnt_reg[3]/Q -type DFF DFF
add mapped point db_write_cnt[4]/q db_write_cnt_reg[4]/Q -type DFF DFF
add mapped point db_write_cnt[5]/q db_write_cnt_reg[5]/Q -type DFF DFF
add mapped point db_write_cnt[6]/q db_write_cnt_reg[6]/Q -type DFF DFF
add mapped point db_write_cnt[7]/q db_write_cnt_reg[7]/Q -type DFF DFF
add mapped point db_write_cnt[8]/q db_write_cnt_reg[8]/Q -type DFF DFF
add mapped point db_write_cnt[9]/q db_write_cnt_reg[9]/Q -type DFF DFF
add mapped point db_write_cnt[10]/q db_write_cnt_reg[10]/Q -type DFF DFF
add mapped point db_write_cnt[11]/q db_write_cnt_reg[11]/Q -type DFF DFF
add mapped point db_write_cnt[12]/q db_write_cnt_reg[12]/Q -type DFF DFF
add mapped point db_write_cnt[13]/q db_write_cnt_reg[13]/Q -type DFF DFF
add mapped point db_write_cnt[14]/q db_write_cnt_reg[14]/Q -type DFF DFF
add mapped point db_write_cnt[15]/q db_write_cnt_reg[15]/Q -type DFF DFF
add mapped point db_write_cnt[16]/q db_write_cnt_reg[16]/Q -type DFF DFF
add mapped point db_write_cnt[17]/q db_write_cnt_reg[17]/Q -type DFF DFF
add mapped point db_write_cnt[18]/q db_write_cnt_reg[18]/Q -type DFF DFF
add mapped point led_blue_wire/q led_blue_wire_reg/Q -type DFF DFF
add mapped point led_green_wire/q led_green_wire_reg/Q -type DFF DFF
add mapped point led_red_wire/q led_red_wire_reg/Q -type DFF DFF
add mapped point led[0]/q led_reg[0]/Q -type DFF DFF
add mapped point led[1]/q led_reg[1]/Q -type DFF DFF
add mapped point led[2]/q led_reg[2]/Q -type DFF DFF
add mapped point led[3]/q led_reg[3]/Q -type DFF DFF
add mapped point led[4]/q led_reg[4]/Q -type DFF DFF
add mapped point led[5]/q led_reg[5]/Q -type DFF DFF
add mapped point led[6]/q led_reg[6]/Q -type DFF DFF
add mapped point led[7]/q led_reg[7]/Q -type DFF DFF
add mapped point led[8]/q led_reg[8]/Q -type DFF DFF
add mapped point led[9]/q led_reg[9]/Q -type DFF DFF
add mapped point led[10]/q led_reg[10]/Q -type DFF DFF
add mapped point led[11]/q led_reg[11]/Q -type DFF DFF
add mapped point led[12]/q led_reg[12]/Q -type DFF DFF
add mapped point led[13]/q led_reg[13]/Q -type DFF DFF
add mapped point led[14]/q led_reg[14]/Q -type DFF DFF
add mapped point led[15]/q led_reg[15]/Q -type DFF DFF
add mapped point master_cmd_packet[2]/q master_cmd_packet_reg[2]/Q -type DFF DFF
add mapped point master_cmd_packet[3]/q master_cmd_packet_reg[3]/Q -type DFF DFF
add mapped point master_cmd_packet[4]/q master_cmd_packet_reg[4]/Q -type DFF DFF
add mapped point master_cmd_packet[5]/q master_cmd_packet_reg[5]/Q -type DFF DFF
add mapped point master_cmd_packet[6]/q master_cmd_packet_reg[6]/Q -type DFF DFF
add mapped point master_cmd_packet[7]/q master_cmd_packet_reg[7]/Q -type DFF DFF
add mapped point master_cmd_packet[8]/q master_cmd_packet_reg[8]/Q -type DFF DFF
add mapped point master_cmd_packet[9]/q master_cmd_packet_reg[9]/Q -type DFF DFF
add mapped point master_cmd_packet[10]/q master_cmd_packet_reg[10]/Q -type DFF DFF
add mapped point master_cmd_packet[11]/q master_cmd_packet_reg[11]/Q -type DFF DFF
add mapped point master_cmd_packet[12]/q master_cmd_packet_reg[12]/Q -type DFF DFF
add mapped point master_cmd_packet[13]/q master_cmd_packet_reg[13]/Q -type DFF DFF
add mapped point master_data_rd[0]/q master_data_rd_reg[0]/Q -type DFF DFF
add mapped point master_data_rd[1]/q master_data_rd_reg[1]/Q -type DFF DFF
add mapped point master_data_rd[2]/q master_data_rd_reg[2]/Q -type DFF DFF
add mapped point master_data_rd[3]/q master_data_rd_reg[3]/Q -type DFF DFF
add mapped point master_data_rd[4]/q master_data_rd_reg[4]/Q -type DFF DFF
add mapped point master_data_rd[5]/q master_data_rd_reg[5]/Q -type DFF DFF
add mapped point master_data_rd[6]/q master_data_rd_reg[6]/Q -type DFF DFF
add mapped point master_data_rd[7]/q master_data_rd_reg[7]/Q -type DFF DFF
add mapped point master_data_rd[8]/q master_data_rd_reg[8]/Q -type DFF DFF
add mapped point master_data_rd[9]/q master_data_rd_reg[9]/Q -type DFF DFF
add mapped point master_data_rd[10]/q master_data_rd_reg[10]/Q -type DFF DFF
add mapped point master_data_rd[11]/q master_data_rd_reg[11]/Q -type DFF DFF
add mapped point master_data_rd[12]/q master_data_rd_reg[12]/Q -type DFF DFF
add mapped point master_data_rd[13]/q master_data_rd_reg[13]/Q -type DFF DFF
add mapped point master_data_rd[14]/q master_data_rd_reg[14]/Q -type DFF DFF
add mapped point master_data_rd[15]/q master_data_rd_reg[15]/Q -type DFF DFF
add mapped point master_data_wr[0]/q master_data_wr_reg[0]/Q -type DFF DFF
add mapped point master_data_wr[1]/q master_data_wr_reg[1]/Q -type DFF DFF
add mapped point master_data_wr[2]/q master_data_wr_reg[2]/Q -type DFF DFF
add mapped point master_data_wr[3]/q master_data_wr_reg[3]/Q -type DFF DFF
add mapped point master_data_wr[4]/q master_data_wr_reg[4]/Q -type DFF DFF
add mapped point master_data_wr[5]/q master_data_wr_reg[5]/Q -type DFF DFF
add mapped point master_data_wr[6]/q master_data_wr_reg[6]/Q -type DFF DFF
add mapped point master_data_wr[7]/q master_data_wr_reg[7]/Q -type DFF DFF
add mapped point master_data_wr[8]/q master_data_wr_reg[8]/Q -type DFF DFF
add mapped point master_data_wr[9]/q master_data_wr_reg[9]/Q -type DFF DFF
add mapped point master_data_wr[10]/q master_data_wr_reg[10]/Q -type DFF DFF
add mapped point master_data_wr[11]/q master_data_wr_reg[11]/Q -type DFF DFF
add mapped point master_data_wr[12]/q master_data_wr_reg[12]/Q -type DFF DFF
add mapped point master_data_wr[13]/q master_data_wr_reg[13]/Q -type DFF DFF
add mapped point master_data_wr[14]/q master_data_wr_reg[14]/Q -type DFF DFF
add mapped point master_data_wr[15]/q master_data_wr_reg[15]/Q -type DFF DFF
add mapped point master_spi_busy/q master_spi_busy_reg/Q -type DFF DFF
add mapped point spi_active/q spi_active_reg/Q -type DFF DFF
add mapped point spi_bitcnt[0]/q spi_bitcnt_reg[0]/Q -type DFF DFF
add mapped point spi_bitcnt[1]/q spi_bitcnt_reg[1]/Q -type DFF DFF
add mapped point spi_bitcnt[2]/q spi_bitcnt_reg[2]/Q -type DFF DFF
add mapped point spi_bitcnt[3]/q spi_bitcnt_reg[3]/Q -type DFF DFF
add mapped point spi_bitcnt[4]/q spi_bitcnt_reg[4]/Q -type DFF DFF
add mapped point spi_cs_n_out[0]/q spi_cs_n_out_reg[0]/Q -type DFF DFF
add mapped point spi_cs_n_out[1]/q spi_cs_n_out_reg[1]/Q -type DFF DFF
add mapped point spi_cs_n_out[2]/q spi_cs_n_out_reg[2]/Q -type DFF DFF
add mapped point spi_cs_n_out[3]/q spi_cs_n_out_reg[3]/Q -type DFF DFF
add mapped point spi_cs_n_out[4]/q spi_cs_n_out_reg[4]/Q -type DFF DFF
add mapped point spi_cs_n_out[5]/q spi_cs_n_out_reg[5]/Q -type DFF DFF
add mapped point spi_cs_n_out[6]/q spi_cs_n_out_reg[6]/Q -type DFF DFF
add mapped point spi_cs_n_out[7]/q spi_cs_n_out_reg[7]/Q -type DFF DFF
add mapped point spi_divcnt[0]/q spi_divcnt_reg[0]/Q -type DFF DFF
add mapped point spi_divcnt[1]/q spi_divcnt_reg[1]/Q -type DFF DFF
add mapped point spi_mosi_out/q spi_mosi_out_reg/Q -type DFF DFF
add mapped point spi_sclk_out/q spi_sclk_out_reg/Q -type DFF DFF
add mapped point spi_shifter_in[0]/q spi_shifter_in_reg[0]/Q -type DFF DFF
add mapped point spi_shifter_in[1]/q spi_shifter_in_reg[1]/Q -type DFF DFF
add mapped point spi_shifter_in[2]/q spi_shifter_in_reg[2]/Q -type DFF DFF
add mapped point spi_shifter_in[3]/q spi_shifter_in_reg[3]/Q -type DFF DFF
add mapped point spi_shifter_in[4]/q spi_shifter_in_reg[4]/Q -type DFF DFF
add mapped point spi_shifter_in[5]/q spi_shifter_in_reg[5]/Q -type DFF DFF
add mapped point spi_shifter_in[6]/q spi_shifter_in_reg[6]/Q -type DFF DFF
add mapped point spi_shifter_in[7]/q spi_shifter_in_reg[7]/Q -type DFF DFF
add mapped point spi_shifter_in[8]/q spi_shifter_in_reg[8]/Q -type DFF DFF
add mapped point spi_shifter_in[9]/q spi_shifter_in_reg[9]/Q -type DFF DFF
add mapped point spi_shifter_in[10]/q spi_shifter_in_reg[10]/Q -type DFF DFF
add mapped point spi_shifter_in[11]/q spi_shifter_in_reg[11]/Q -type DFF DFF
add mapped point spi_shifter_in[12]/q spi_shifter_in_reg[12]/Q -type DFF DFF
add mapped point spi_shifter_in[13]/q spi_shifter_in_reg[13]/Q -type DFF DFF
add mapped point spi_shifter_in[14]/q spi_shifter_in_reg[14]/Q -type DFF DFF
add mapped point spi_shifter_in[15]/q spi_shifter_in_reg[15]/Q -type DFF DFF
add mapped point spi_shifter_out[0]/q spi_shifter_out_reg[0]/Q -type DFF DFF
add mapped point spi_shifter_out[1]/q spi_shifter_out_reg[1]/Q -type DFF DFF
add mapped point spi_shifter_out[2]/q spi_shifter_out_reg[2]/Q -type DFF DFF
add mapped point spi_shifter_out[3]/q spi_shifter_out_reg[3]/Q -type DFF DFF
add mapped point spi_shifter_out[4]/q spi_shifter_out_reg[4]/Q -type DFF DFF
add mapped point spi_shifter_out[5]/q spi_shifter_out_reg[5]/Q -type DFF DFF
add mapped point spi_shifter_out[6]/q spi_shifter_out_reg[6]/Q -type DFF DFF
add mapped point spi_shifter_out[7]/q spi_shifter_out_reg[7]/Q -type DFF DFF
add mapped point spi_shifter_out[8]/q spi_shifter_out_reg[8]/Q -type DFF DFF
add mapped point spi_shifter_out[9]/q spi_shifter_out_reg[9]/Q -type DFF DFF
add mapped point spi_shifter_out[10]/q spi_shifter_out_reg[10]/Q -type DFF DFF
add mapped point spi_shifter_out[11]/q spi_shifter_out_reg[11]/Q -type DFF DFF
add mapped point spi_shifter_out[12]/q spi_shifter_out_reg[12]/Q -type DFF DFF
add mapped point spi_shifter_out[13]/q spi_shifter_out_reg[13]/Q -type DFF DFF
add mapped point spi_shifter_out[14]/q spi_shifter_out_reg[14]/Q -type DFF DFF
add mapped point spi_shifter_out[15]/q spi_shifter_out_reg[15]/Q -type DFF DFF
add mapped point spi_state[0]/q spi_state_reg[0]/Q -type DFF DFF
add mapped point spi_state[1]/q spi_state_reg[1]/Q -type DFF DFF
add mapped point spi_state[2]/q spi_state_reg[2]/Q -type DFF DFF
add mapped point timer_cnt[0]/q timer_cnt_reg[0]/Q -type DFF DFF
add mapped point timer_cnt[1]/q timer_cnt_reg[1]/Q -type DFF DFF
add mapped point timer_cnt[2]/q timer_cnt_reg[2]/Q -type DFF DFF
add mapped point timer_cnt[3]/q timer_cnt_reg[3]/Q -type DFF DFF
add mapped point timer_cnt[4]/q timer_cnt_reg[4]/Q -type DFF DFF
add mapped point timer_cnt[5]/q timer_cnt_reg[5]/Q -type DFF DFF
add mapped point timer_cnt[6]/q timer_cnt_reg[6]/Q -type DFF DFF
add mapped point timer_cnt[7]/q timer_cnt_reg[7]/Q -type DFF DFF
add mapped point timer_cnt[8]/q timer_cnt_reg[8]/Q -type DFF DFF
add mapped point timer_cnt[9]/q timer_cnt_reg[9]/Q -type DFF DFF
add mapped point timer_cnt[10]/q timer_cnt_reg[10]/Q -type DFF DFF
add mapped point timer_cnt[11]/q timer_cnt_reg[11]/Q -type DFF DFF
add mapped point timer_cnt[12]/q timer_cnt_reg[12]/Q -type DFF DFF
add mapped point timer_cnt[13]/q timer_cnt_reg[13]/Q -type DFF DFF
add mapped point timer_cnt[14]/q timer_cnt_reg[14]/Q -type DFF DFF
add mapped point timer_cnt[15]/q timer_cnt_reg[15]/Q -type DFF DFF
add mapped point timer_cnt[16]/q timer_cnt_reg[16]/Q -type DFF DFF
add mapped point timer_cnt[17]/q timer_cnt_reg[17]/Q -type DFF DFF
add mapped point timer_cnt[18]/q timer_cnt_reg[18]/Q -type DFF DFF
add mapped point timer_cnt[19]/q timer_cnt_reg[19]/Q -type DFF DFF
add mapped point timer_cnt[20]/q timer_cnt_reg[20]/Q -type DFF DFF
add mapped point timer_cnt[21]/q timer_cnt_reg[21]/Q -type DFF DFF
add mapped point timer_cnt[22]/q timer_cnt_reg[22]/Q -type DFF DFF
add mapped point timer_cnt[23]/q timer_cnt_reg[23]/Q -type DFF DFF
add mapped point timer_cnt[24]/q timer_cnt_reg[24]/Q -type DFF DFF
add mapped point timer_cnt[25]/q timer_cnt_reg[25]/Q -type DFF DFF
add mapped point timer_cnt[26]/q timer_cnt_reg[26]/Q -type DFF DFF
add mapped point timer_cnt[27]/q timer_cnt_reg[27]/Q -type DFF DFF
add mapped point timer_cnt[28]/q timer_cnt_reg[28]/Q -type DFF DFF
add mapped point timer_cnt[29]/q timer_cnt_reg[29]/Q -type DFF DFF
add mapped point timer_cnt[30]/q timer_cnt_reg[30]/Q -type DFF DFF
add mapped point timer_cnt[31]/q timer_cnt_reg[31]/Q -type DFF DFF
add mapped point master_cmd_packet[1]/q master_cmd_packet_reg[1]/Q -type DFF DFF
add mapped point spi_divcnt[2]/q spi_divcnt_reg[2]/Q -type DFF DFF
add mapped point timer_running/q timer_running_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
